### ISSUE TITLE
Incorrect Ireland hydro storage

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#1340]
In the last couple of days Ireland has not reported putting energy into hydro storage. It's either near-zero or discharging, and, suspiciously, it regularly discharges in the middle of the night. Can someone take a look at historical data in ENTSOE and see if there is a problem with either their reporting or our interpretation of it? Or is it just that they charged it up earlier in the year or last year and are only releasing now?

**Comment by alixunderplatz** [comment]
Well spotted, @jarek !

Using the visualization from http://energodock.com/ireland/electricity-generation, the pattern you described is totally clear:

![image](https://user-images.githubusercontent.com/25743609/38954947-751c94ea-4353-11e8-9a17-30d71368fcf0.png)

Full power in the early morning hours (with cheapest prices), some smaller peaks during the day during hours of peak demand (with high prices).

It's very clear to me: Pumping and generation are both reported under "pumped storage generation".
That's why "pumped storage consumption" has always been empty. 
So this should be an issue on Eirgrid's/ENTSO-E's side and must be adressed to them.

**Comment by brunolajoie** [comment]
Hello @Dalius-ENTSO-E, I thought you might be interested in this finding! Eirgrid data (and therefore ENTSOE) seems to report both charging and discharging of Irish's PHS plants in the same category: pumped storage _generation_

**Comment by jarek** [comment]
Unfortunately this is still an issue with wrong data being submitted to ENTSOE

**Comment by jarek** [comment]
Ireland is now back in ENTSOE, but still submitting wrong data:

![image](https://user-images.githubusercontent.com/47415/42737958-137ad08a-887c-11e8-8aa9-be3324ba07b7.png)

**Comment by corradio** [comment]
I've asked Twitter for help.

**Comment by alixunderplatz** [comment]
:)

![image](https://user-images.githubusercontent.com/25743609/47744741-5e415800-dc82-11e8-9fef-f85e332300ea.png)

**Comment by jarek** [comment]
Generally it is important to stay positive, but perhaps not in this exact case... The issue being of course that we have no way of telling which is storage and which is production.

**Comment by alixunderplatz** [comment]
This problem still persists. No more answers from EirGrid on my tweet since 12th November 2018.
https://twitter.com/alixunderplatz/status/1062075074092634113

I think it makes sense to disable hydro pumped storage for Ireland for now.
Maybe you could try to ask another time via twitter in the name of electricitymap.

![image](https://user-images.githubusercontent.com/25743609/51208740-c4975780-190e-11e9-8c73-0c8d80c24c82.png)

When adding usual hydro to the graph, you can see clearly what is "peak generation" and what is pumping in the pumped storage category in low-demand times at night. 

![image](https://user-images.githubusercontent.com/25743609/51209169-e6dda500-190f-11e9-96ed-dae957596c88.png)

**Comment by Dalius-ENTSO-E** [comment]
Hi Chanpreet,
Please note, that EriGrid reports pumping mode (which should be reported as consumption part) as generation which is absolutely incorrect. See users observations below:
[cid:image001.png@01D4AD7A.CC4BC4C0]

Could you please contact EirGrid and advise them how the pumping mode should be reported? They have to report this as consumption, but not as a negative generation. Negative values are not allowed and will be rejected.

https://twitter.com/EirGrid/status/1062014059116142592

Thanks
Best regards,

Dalius Sulga, Ph.D
Data and Transparency Platform Senior Advisor
Team lead

ENTSO-E
Avenue de Cortenbergh 100 ● 1000 Brussels ● Belgium
Tel +32 2741 86 26 ● Mobile +32 496 52 44 93

entsoe.eu<http://www.entsoe.eu/> | Twitter<https://twitter.com/ENTSO_E> | LinkedIn<https://www.linkedin.com/company/entso-e> | YouTube<https://www.youtube.com/user/ENTSOE> | Slideshare<http://www.slideshare.net/ENTSO-E>

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by jarek** [comment]
Update: looking recently, Ireland's hydro storage in the middle of the night has been reported as 0. It looks like instead of reporting hydro storage always positive as before, they set the reported value to minimum zero. That's less wrong, but not strictly correct...

**Comment by alixunderplatz** [comment]
Just found another answer from 25th Feb to my tweet. @jarek the have fixed the problem almost like you described:

https://twitter.com/EirGrid/status/1100005872149905408
"Hi Alex. This has now been corrected so only positive generation values are included when we report on Pumped Hydro generation. Many thanks, the EirGrid team."

So since 5th February it seems only production is reported, but no pumping power - but that's how it is for some other ENTSOE-countries with little pumped storage capacity (PL, BE, GB, ...) as well.

Are we closing this? I think it's a large effort we could help detecting & fixing this, because many statistics were based on the false pumped storage production. 👍

**Comment by alixunderplatz** [comment]
This has been fixed a whole while ago. We see positive and negative values on the map now.
Closing.
