### ISSUE TITLE
Data for Iceland

### ISSUE THREAD

**Issue by HenkPoley** [tmrowco/electricitymap-contrib#1511]
Found some data for Iceland wind generation: https://www.landsvirkjun.com/researchdevelopment/research/windpower/realtimedata/

If there is other live data it's probably at Landsnet: https://www.landsnet.is/english/

**Comment by alixunderplatz** [comment]
Hi @HenkPoley !
There was an issue #140 which was closed a while ago that dealt with Iceland, including these links you found :)
There still is no further breakdown by type for geothermal and hydro production, which is why including Iceland is no option at the moment, so I'll close. Feel free to re-open if I have overlooked something.
