### ISSUE TITLE
No data for Moldova (MD) on the map

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1517]
Looks like the data source is still providing real-time data:

http://www.moldelectrica.md/ro/activity/system_state
http://www.moldelectrica.md/utils/load4

Why is MD not displayed on the map anymore?

**Comment by jarek** [comment]
It looks like the backend can't connect: [logs 24 hours up to now](https://kibana.electricitymap.org/app/kibana#/discover/1710fdd0-2460-11e8-a779-9d01de8d7a71?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-21T18:01:59.140Z',mode:absolute,to:'2018-07-22T18:01:59.140Z'))&_a=(columns:!(level,extra.key,message),filters:!(('$state':(store:appState),exists:(field:level),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!f,type:exists,value:exists)),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!t,params:(query:INFO,type:phrase),type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:extra.key,negate:!f,params:(query:MD,type:phrase),type:phrase,value:MD),query:(match:(extra.key:(query:MD,type:phrase))))),index:'93e631f0-245f-11e8-a779-9d01de8d7a71',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))) have lots of `HTTPConnectionPool(host='www.moldelectrica.md', port=80): Max retries exceeded with url: /ro/activity/system_state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f672a5c5e48>: Failed to establish a new connection: [Errno 111] Connection refused',))`

When I ran it locally it worked fine once but then gave me the exception on second attempt. Maybe the website has a hosting problem and requests often can't resolve?

**Comment by systemcatch** [comment]
I ran the parser 7 times in 1 minute, 2 connections refused and 5 succeeded. Interestingly after a refusal the next run 5 seconds later worked perfectly. We could setup some kind of try/except to get past this?

**Comment by corradio** [comment]
That's interesting. The parser runs often, so occasional connection refusals should not be a problem.
Maybe we got banned?
@jarek Do the requests from the server sometimes go through, or do they always fail?

**Comment by systemcatch** [comment]
@corradio how often is the parser running?

**Comment by corradio** [comment]
It depends. It runs continuously and calls the parsers in parallel but waits for them all to finish before sending out a new request batch.

**Comment by systemcatch** [comment]
Given that the page we use is requested every minute by the main site map display it shouldn't be overloading them. However there is unlikely to be any other requests for that data bar us and the main site.

**Comment by jarek** [comment]
My test requests sometimes went through and completed successfully.

Right now it looks like the server got one data point overnight as well. It seems to have been 23:15 Berlin time, which suspiciously is just after midnight in Moldova. Maybe they have a daily limit of requests which we are quickly exhausting? But that would be silly.

![image](https://user-images.githubusercontent.com/47415/43342700-f1d67a62-91e3-11e8-8bba-237e1b3dd981.png)

**Comment by systemcatch** [comment]
The parser has to load http://www.moldelectrica.md/ro/activity/system_state first to get cookies so it can then load http://www.moldelectrica.md/utils/load4 with data. All the errors seem to happen with the system_state link so if we had a try/except with a suitable delay to retry again (say 3 times) that may solve the problem? As long as it's not excessive I don't see that being a problem.

**Comment by alixunderplatz** [comment]
Seems fixed ;)

![image](https://user-images.githubusercontent.com/25743609/43796871-cbcd5dd6-9a85-11e8-95d0-9d92d2d07a5a.png)
