### ISSUE TITLE
Add new battery in South Australia to /parsers/lib/AU_battery.py

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1518]
The Dalrymple ESCRI-SA Battery Project was recently commisioned in South Australia, see:
https://reneweconomy.com.au/south-australias-second-big-battery-charges-into-action-79148/
(some more upcoming battery projects are mentioned in the news article as well)

Link to the project website and real-time data dashboard:
https://www.escri-sa.com.au/

There is a seperate link to some custom graphs. It says granular data will be available from 1st August for download.
https://www.escri-sa.com.au/data

We should add this battery to [AU_battery.py](https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/lib/AU_battery.py). I had a look at various timestamps and I am absolutely sure the abbreviation of the JSON for the battery is **"DALNTH"** (most likely for Dalrymple North).
Should be easy to implement!

Compare these two sources for the 18th of July from the project website and the nemlog data source
(we also use this for hornsdale battery):

https://www.escri-sa.com.au/data/
and
http://nemlog.com.au/api/unit/DALNTH/20180718/20180718/json

**Comment by lorrieq** [comment]
Hey @alixunderplatz, I'll take this one.

What's the difference between **DALNTH01** and **DALNTHL1** in the json? **DALNTH01** seems to always be zero, maybe we just want to ping [**DALNTHL1**](http://nemlog.com.au/api/unit/DALNTHL1/20180718/20180718/json)?

We have to decide what we want to do when some batteries return values and some return `None` due to a failed API request. For now I just set the `None` values to zero.

Created an initial PR as a work in progress.

**Comment by alixunderplatz** [comment]
Hi @lorrieq, no idea what the difference is, but let's go for DALNTHL1 then! Thanks for taking this and for your PR! :)

**Comment by lorrieq** [comment]
closed by #1519
