### ISSUE TITLE
Nuclear Energy - RED

### ISSUE THREAD

**Issue by energyrevolution** [tmrowco/electricitymap-contrib#1526]
Dear Electricitymap Team,
I would like you to change the colour-code of the Electricitymap in a way, that the harmful nuclear energy is not giving the psychologically most positive GREEN colour, but to be changed to RED for those countries which use Uranium or other substances for their nuclear power plants.
Thank you
Warm regards

**Comment by corradio** [comment]
Hello Krisztina,
Thank you for reaching out.
I understand your concern (and we have a lot of requests that echo your remarks).
In our FAQ you can read that:

## Why are nuclear-powered countries shown as green on the map?
> Nuclear energy production has a very low carbon intensity (source), and nuclear-powered countries are therefore shown as green on the map. This does not mean that there are not other environmental challenges associated nuclear energy (as is also the case with other forms of energy production), but these challenges are unrelated to the emissions of greenhouse gases and are therefore outside the scope of this map.

Our focus is solely on carbon emissions. We do not make judgments about nuclear being bad, because then we would end up requiring to do an endless assessment for what "bad" means on all forms on electricity production. For example, building a hydro dam has ecological consequences that should not be disregarded.
Therefore we focus solely on CO2 emissions.

Best,

Olivier Corradi
