### ISSUE TITLE
Question regarding SPP

### ISSUE THREAD

**Issue by uswoods** [tmrowco/electricitymap-contrib#1648]
This may be offtopic, but does anybody how the price contours at http://pricecontourmap.spp.org/pricecontourmap/ are calculated? Do they play any role in reality?

**Comment by alixunderplatz** [comment]
Hi @uswoods !
The key term to look for regarding these price countours of SPP is "nodal pricing". A "node" usually is a substation within the high voltage grid.
It is based on grid constraints as well as bids for consumption and generation on one node of the grid instead of a unique price for the grid/bidding zone as a whole. So this pricing model is "connecting" load and generation on local levels and can be helpful to avoid re-dispatch.

For further info check:
https://en.wikipedia.org/wiki/Electricity_market#Bid-based,_security-constrained,_economic_dispatch_with_nodal_prices

I hope this was helpful ;)
Kind regards, Alex

**Comment by alixunderplatz** [comment]
@uswoods Feel free to comment if anything is unclear. I'm closing this issue for now.
