### ISSUE TITLE
Strange behavior of Portugal data 

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1658]
Could that be wind curtailment? Or, more realistically, data issue?

![image](https://user-images.githubusercontent.com/22095643/47621197-96b32b80-daf4-11e8-8cdb-65dd46a0e7c8.png)

**Comment by jarek** [comment]
Listed installed capacity of wind is 5.03 GW and on that bump it reported producing 5.59 GW, the hour before was 3.4 GW and the hour after 2.6 GW. During that hour there was also reported 1.12 GW of hydro storage charging, while the hour before was 83 MW charging and the hour after was 270 MW charging. It looks like the wind point is an error.

**Comment by jarek** [comment]
Actually I'm willing to bet this is double-counting due to time zone change. That high point contains wind production from 2:00 to 3:00 before the change and the production from 2:00 to 3:00 after the change added up.

Italy was also weird during that time.

I also saw the following thing, which I'm betting is related to time change, but reporting just in case: weird display issue for Portugal history right now, see bottom left corner of the axes:

![](https://user-images.githubusercontent.com/47415/47622508-32dd3280-daf5-11e8-9c0c-d9f98c59d4b1.png)

The DOM has two labels for "12:00 AM":

![](https://user-images.githubusercontent.com/47415/47622513-4a1c2000-daf5-11e8-8f95-2f3d5a08398f.png)

Time of screenshot is around 22:00 UTC, with data timestamped 21:53 UTC, timezone of the browser is UTC-1.

**Comment by brunolajoie** [comment]
Closing as it's probably timezone change related !
