### ISSUE TITLE
CO2eq per kWh at per-state level

### ISSUE THREAD

**Issue by kylemcdonald** [tmrowco/electricitymap-contrib#1702]
The EPA maintains information about the CO2eq per kWh on a per-state level https://www.epa.gov/energy/emissions-generation-resource-integrated-database-egrid 

Check eGRID2016_summarytables table 3, with data from 2016.

State | CO2e (lb/MWh)
--- | ---
AK | 930.0
AL | 917.5
AR | 1,122.6
AZ | 937.1
CA | 454.1
CO | 1,477.9
CT | 502.1
DC | 483.0
DE | 889.3
FL | 1,029.0
GA | 1,007.4
HI | 1,532.9
IA | 1,003.9
ID | 189.3
IL | 816.0
IN | 1,824.9
KS | 1,204.1
KY | 1,968.1
LA | 882.1
MA | 827.5
MD | 1,019.5
ME | 347.6
MI | 1,106.0
MN | 1,020.3
MO | 1,699.0
MS | 943.0
MT | 1,260.1
NC | 872.7
ND | 1,674.8
NE | 1,290.7
NH | 316.8
NJ | 559.8
NM | 1,582.6
NV | 771.5
NY | 465.9
OH | 1,475.3
OK | 1,048.3
OR | 307.2
PA | 860.0
RI | 871.7
SC | 632.8
SD | 516.6
TN | 998.4
TX | 1,054.6
UT | 1,638.4
VA | 819.0
VT | 66.8
WA | 187.9
WI | 1,396.5
WV | 1,990.6
WY | 2,041.0
__U.S.__ | 1,004.2

Your data lists [CA](https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json) as 244 gCO2eq/kWh but the EPA reports closer to 206 gCO2eq/kWh. You list NY at 200, here it's closer to 210.

Is the Tomorrow data more up to date than the EPA data? Which one is more accurate? Would a pull request with these values added to the `co2eq_parameters.json` be welcome, or is it automatically generated?

**Comment by brunolajoie** [comment]
Thanks for noticing.
Difference can come from two main factors:

1/ We take into account imports, in order to compute carbon intensity of electricity consumed, while I bet EPA reports the carbon intensity of electricity produced.

2/ We use IPCC's emission factor per main type power plant below.
EPA probably uses its own emission factor that might differ.
![ipcc 2014 powerplant ghg intensity](https://user-images.githubusercontent.com/22095643/49784406-72668380-fd1d-11e8-8371-d9349dd7dd80.PNG)
