### ISSUE TITLE
Internat. Energy Agency (IEA) not a reputable source

### ISSUE THREAD

**Issue by conrad-heimbold** [tmrowco/electricitymap-contrib#1784]
I saw the IEA a couple of times mentioned as source in some threads here. 

However, I think we should be skeptical about the IEA and if it is a reputable source, taking into consideration the systematically wrong predictions that the IEA made in the past: https://en.wikipedia.org/wiki/International_Energy_Agency#Critics 

I think it is safe to say that the IEA had a political agenda when they made their wrong predictions.

**Comment by conrad-heimbold** [comment]
It would be good to implement some kind of meta-tags inside the data where you can also safe the source of the data. This way, if one source of data is proven to be inconsistent / wrong, you can find out easily where else its data has been used.

**Comment by jarek** [comment]
Hello,

Thank you for the note.

To clarify, we have used IEA statistics on past generation to estimate carbon footprint of "unknown" fuel or in cases where energy is imported from a region where we don't have data.

As an example, we've used https://www.iea.org/statistics/?country=ZAMBIA&year=2016&category=Key%20indicators&indicator=ElecGenByFuel&mode=table&dataTable=ELECTRICITYANDHEAT (tab "Data tables") for Namibia's imports from Zambia - indicating that vast majority of Zambia's generation is hydro. (And conversely, that majority of Namibia's imports from South Africa have been generated from coal.)

You can find the cases where it has been used in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json searching for "IEA". Note that the IEA data for "RU" is not used because it's now split into "RU-1" and "RU-2".

It is also used in https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/SV.py to back-up the claim that El Salvador's "thermal" generation is all from oil. Same with Uruguay per #1342, and Iraq per #1434.

Are there also claims that IEA's statistics on past generation are wrong?

I suppose they might not include behind-the-meter renewable generation, but the situation with reporting that is unfortunately inconsistent anyway (some grid operators estimate it and report it, some don't, Electricity Map generally doesn't include what grid operators don't report).

**Comment by brunolajoie** [comment]
I'm closing this issue, as it does not refers to a specific issue in our code base. Feel free to re-open another issue with more precide details on what to "fix"?

**Comment by conrad-heimbold** [comment]
Thank you for your answer brunolajoie, if I have some time I will take a look into the issues / code to find the data coming from the IEA that might be wrong.
