### ISSUE TITLE
Midnight glitch in UK-GB data

### ISSUE THREAD

**Issue by bmckinlay** [tmrowco/electricitymap-contrib#1844]
Reported wind generation drops to zero every day at midnight. 

<img width="361" alt="Screenshot 2019-05-04 at 13 22 17" src="https://user-images.githubusercontent.com/13368547/57179023-fd811b00-6e70-11e9-99f7-814c0cfcd3cd.png">

Possibly related to #1779?

**Comment by jld3103** [comment]
And maybe also related to #1754

**Comment by systemcatch** [comment]
@lorrieq any ideas here?

**Comment by lorrieq** [comment]
Apologies for the late reply, been a bit out of the loop. I presume the issue is the lookback to yesterday needs to be more liberal or we change it to look back a set number of hours. Hopefully I will be able to take a look later.

![image](https://user-images.githubusercontent.com/6525086/58087877-67136000-7bb9-11e9-8b8d-2f97ba3ae9a3.png)
