### ISSUE TITLE
Language selection is not persistent

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#1858]
After selecting e.g. a German translation, the `&lang=DE` part quickly appears in my Chrome browser address bar before disappearing again.

The app gets translated but the language context is lost, so when I refresh the page, I'm back to the English version.

1. Keeping language as a query param seems like the right approach to me - it's probably a bug that it gets dropped
2. Alternatively, the language selection could be persisted to the browser cache and picked up upon app load - the downside would be that it wouldn't persist when links are shared

p.s. It's not directly related, but it would be nice to see which language is currently selected in the dropdown at all times - that would probably reduce confusion with partial translations (_did I really click on language X, everything I see is still in English?_ :thinking:)

![image](https://user-images.githubusercontent.com/1216874/57972718-8b472500-799e-11e9-9194-ad69df65ca98.png)

**Comment by corradio** [comment]
Indeed the proper behaviour would be set a cookie that remembers the language.
It's important not to have it in the URL as people share the website on social media and the language shouldn't be part of that.

**Comment by fbarl** [comment]
> It's important not to have it in the URL as people share the website on social media and the language shouldn't be part of that

My first instinct was actually against that - thinking of language selection as a part of a user view context, I would expect everyone who opens my link to see exactly what I'm seeing.

However, I was curious what internet said, so after a quick research I came across [this discussion](https://ux.stackexchange.com/questions/29281/sharing-links-on-facebook-with-multi-language-site) which made me see the other side as well :)

I guess a solution that might work for everyone would be to store the setting in a cookie, but instead of always defaulting to english for new users, use `navigator.language(s)` to make the best call on first open, although this [doesn't seem as straightforward as it sounds](https://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference) - WDYT @corradio?

**Comment by corradio** [comment]
Hey @fbarl,
The i18n node package for express inspects the accept-language header sent by the browser and sets language accordingly (it doesn't set English by default).
I've just looked a bit at the code and because there's also server side translations (using the ejs templating system), it won't work to just set the cookie. We'd have to also add a redirection if the cookie value is different from the value injected from server.
That's all a bit cumbersome but would nice to clean up.
We could do the redirection "hack", or we could do things cleanly and have translations either server side or client-side (but not both).
