### ISSUE TITLE
NL renewable power estimates

### ISSUE THREAD

**Issue by dguzs** [tmrowco/electricitymap-contrib#1871]
Hello,

electricityMap lacks info on renewable power sources for the Netherlands. I suggest this information can be taken from http://energieopwek.nl/

BR
Dmitrijs Guzs

**Comment by MartienVisser** [comment]
Thanks, as I'm the author of Energieopwek.nl :).

Actually, the Dutch CO2-emission per kWh is much lower than currently suggested. I think it is not too difficult to improve the data on electricitymap.org substantially using the information below:

1) currently, about 20% of electricity is generated by renewable sources (solar: 5%, biomass: 6%, onshore wind: 6% and offshore wind: 3%.
2) the Dutch coal fired power stations are new and have high efficiency (CO2 = 700 gram/kWh); moreover, they use some co-firing of biomass (see Energieopwek.nl); this is currently around 425 MW, thus 10% of the total coal-fired capacity in the NL.
3) gas-fired power in the Netherlands is generated by a mixture of cogeneration (300 gram/kWh) and high efficiency gas-fired power stations (<400 gram/kWh).

Real-time data of Dutch power stations is not publicly available due to regulation (coal-fired) and because Dutch cogen plants use a significant portion of their electricity production themselves; thus, the DSOs and TSOs don't see it. I do not expect a quick solution for this.

However, a good approximation could be using a fixed volume of 20% renewable, adding coal (90% of capacity at 700 gr/kWh) and the rest by gas (50.50 mixture STEG & Cogen) at average of 350 gr/kWh). 

If required, variable (solar and wind) in the Netherlands could be modelled using energieopwek.nl, or, maybe simpler, using the average utilisation factor of Belgium, UK and Germany.  

By the way, my estimate/calculated specific CO2 of Dutch electricity generation in April 2019 was about 375 gram/kWh. I publish this information monthly (in English) at the website of Entrance: https://www.en-tran-ce.org/onderzoek/duurzame-energie-in-nederland/

Best regards,

Martien Visser

**Comment by jarek** [comment]
See also past and more recent comments about Netherlands data in #78

To confirm, @MartienVisser - is the data of renewable production on Energieopwek.nl official or estimated?

**Comment by MartienVisser** [comment]
The data is calculated using models which are based on wind speed and solar radiation data from about 40 weather stations distributed over the Netherlands and offshore. The results have been calibrated against monthly (wind) and annual (solar) data from the national statistical office CBS.

**Comment by dguzs** [comment]
Hello,

How difficult would it be to implement this data into the map?

Br
Dmitrijs

**Comment by systemcatch** [comment]
> Real-time data of Dutch power stations is not publicly available due to regulation (coal-fired)

@MartienVisser can you expand on this, the data is not available due to pressure from the coal lobby?

> How difficult would it be to implement this data into the map?

@dguzs the data is not difficult to integrate, the question is whether we should. Generally we've tried to avoid mixing data sources.

Currently NL has a CO2 intensity as follows;

```json
"NL": {
        "hydro discharge": {
          "source": "2017 average by Tomorrow",
          "value": 462.73049119238584
        },
        "unknown": {
          "_comment": "Source: Derived from 2017 annual average: coal  30.0%, co-generation(gas)  19.0%, gas 28.0%, coke-oven-gas 5.0%, nuclear 4.0%, Wind  7.7%, biomass (waste) 4.90%, solar 1.40%.",
          "_url": "http://en-tran-ce.org/newsletter-renewable-energy-in-the-netherlands/",
          "source": "assumes 57% gas, 33% coal, 5% biomass, 4% nuclear",
          "value": 563
        }
}
```

The `source` key needs correcting to mention renewables. Maybe we could try using Martien's numbers instead.

@alixunderplatz any thoughts?

**Comment by MartienVisser** [comment]
Dear Chris, this is not due pressure of ‘the coal lobby’. The reason is that in the Netherlands, there are just three companies (RWE, Uniper and Engie) with large coal-fired power stations. So, if TenneT would start publishing data from the utilization of coal-fired stations, it will be relatively easy for them to exactly find out how the two other competitors are (strategically) using their equipment. This might distort the electricity market. Whether this distortion is serious enough, not to publish the data is open for debate. So far, our market regulator has not taken the step to allow TenneT to publish this data. So, in their view, this distortion is too large. Martien



Van: Chris <notifications@github.com>
Verzonden: donderdag 27 juni 2019 11:23
Aan: tmrowco/electricitymap-contrib <electricitymap-contrib@noreply.github.com>
CC: Visser BM, Martien <b.m.visser@pl.hanze.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [tmrowco/electricitymap-contrib] NL renewable power sources electricityMap (#1871)


Real-time data of Dutch power stations is not publicly available due to regulation (coal-fired)

@MartienVisser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartienVisser&data=02%7C01%7Cb.m.visser%40pl.hanze.nl%7Cd278e31ceda8402011a308d6fae118ce%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C636972242029819053&sdata=9Ntp8Ico59S3R2sj7unkIeHTQsmiFY92t8snLETF5j0%3D&reserved=0> can you expand on this, the data is not available due to pressure from the coal lobby?

How difficult would it be to implement this data into the map?

@dguzs<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdguzs&data=02%7C01%7Cb.m.visser%40pl.hanze.nl%7Cd278e31ceda8402011a308d6fae118ce%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C636972242029819053&sdata=i9nj1mcy183NJJPnJfDDAxXLwxZsEc5GuOgk%2Bbl7XSw%3D&reserved=0> the data is not difficult to integrate, the question is whether we should. Generally we've tried to avoid mixing data sources.

Currently NL has a CO2 intensity as follows;

"NL": {

        "hydro discharge": {

          "source": "2017 average by Tomorrow",

          "value": 462.73049119238584

        },

        "unknown": {

          "_comment": "Source: Derived from 2017 annual average: coal  30.0%, co-generation(gas)  19.0%, gas 28.0%, coke-oven-gas 5.0%, nuclear 4.0%, Wind  7.7%, biomass (waste) 4.90%, solar 1.40%.",

          "_url": "http://en-tran-ce.org/newsletter-renewable-energy-in-the-netherlands/",

          "source": "assumes 57% gas, 33% coal, 5% biomass, 4% nuclear",

          "value": 563

        }

}

The source key needs correcting to mention renewables. Maybe we could try using Martien's numbers instead.

@alixunderplatz<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falixunderplatz&data=02%7C01%7Cb.m.visser%40pl.hanze.nl%7Cd278e31ceda8402011a308d6fae118ce%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C636972242029829049&sdata=gbBCDx%2FmzD2ffKQ%2FpHpFzkGKoYEB%2BI1gBAoVODbyg6c%3D&reserved=0> any thoughts?

**Comment by PaulCornelissen** [comment]
So I've created a parser for the data from energieopwek.nl because it's simply the best source of data available for renewables currently. I've only used the data for wind and solar, because it's not clear that the other sources only represent power production and fully cover all power production from bio sources.

The new parser is fully back-wards compatible with the old ENTSOE parser, so we can always switch back very easily by switching one boolean from true to false if the data quality of ENTSOE improves.

While working on this I've found that ENTSOE does publish seemingly very accurate data for nuclear power production real-time. So I want to suggest to enable the parsing and publishing of this data and removing the estimate of 4% nuclear from the unknown sources. This is as simple as removing this line (line 110 in NL.py):
`p['production']['nuclear'] = None`

Also ENTSOE is publishing some data for Gas. Is this data complete bogus or is this just a subset of the gas generators and is the data only ever too low? If it's to low then we could simply parse these numbers and publish them as gas generation and only put the remainder under unknown.

Also I know that it's preferable to use only data from a single source, but it's not without precedent. It's also done for Australia. In any case I think it has been sufficiently demonstrated that the current CO2 estimate for NL is wrong by a significant margin. I would prefer to improve the calculation as best we can with the available data, but if not that, then it would be better to stop suggesting we know the CO2 intensity of the NL electricity production when we don't.

**Comment by PaulCornelissen** [comment]
So today is a good example of ENTSOE data being way of:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/5185181/64906066-a114ee80-d6e1-11e9-8603-dc46ae7d1ad9.png">
ENTSOE doesn't show any solar generation in the past 24h, even though today is sunny and yesterday was also sunny. Yesterday we had wind, but that also doesn't show properly. ENTSOE only shows about 250MW while it was probably more like 800MW (on- and offshore combined).
<img width="523" alt="image" src="https://user-images.githubusercontent.com/5185181/64906041-31066880-d6e1-11e9-84d0-e5d318ece8fe.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/5185181/64906044-395ea380-d6e1-11e9-81e9-49f647796c57.png">

**Comment by corradio** [comment]
Hi @MartienVisser @PaulCornelissen !

Thank you for your super useful comments. I've been swamped lately and not really able to look at this quickly enough. Let's validate the PR quickly so we can correct this discrepancy.

Olivier

**Comment by PaulCornelissen** [comment]
Hi Olivier,

Yes let's do this! :) 

Do you have an opinion on this? Should I enable it? Or should we have a separate discussion on this subject?:
> While working on this I've found that ENTSOE does publish seemingly very accurate data for nuclear power production real-time. So I want to suggest to enable the parsing and publishing of this data and removing the estimate of 4% nuclear from the unknown sources. This is as simple as removing this line (line 110 in NL.py):
> `p['production']['nuclear'] = None`

And this:
> Also ENTSOE is publishing some data for Gas. Is this data complete bogus or is this just a subset of the gas generators and is the data only ever too low? If it's to low then we could simply parse these numbers and publish them as gas generation and only put the remainder under unknown.

Paul

**Comment by corradio** [comment]
I think you can go ahead with nuclear if we have enough evidence that the data is correct.
@MartienVisser , as you know much more than we do, are you able to tell us if the ENTSOE data is sufficiently correct?

Olivier

**Comment by PaulCornelissen** [comment]
@corradio I've created another PR that fixes some minor issues and copies nuclear production from ENTSOE data.

It doesn't yet use ENTSOE data for Gas powered generation, because through back-testing I found that sometimes the sum of Net-imports + Solar + Wind + Nuclear + Gas is higher than consumption which can't be. I suspect that is because ENTSOE consumption data doesn't see behind the meter consumption, but energieopwek.nl estimate tries to estimate solar production for all solar including self-consumed power. 

In any case if this goes live we need to redetermine the CO2 intensity of "unknown" because nuclear will be directly accounted for and also to possibly include the improvements suggested by @MartienVisser

**Comment by MartienVisser** [comment]
Yes, I think the nuclear data on the ENTSOE website are correct. The Netherlands has only one nuclear power station with a nominal capacity of 485 MW. Martien

Van: Olivier Corradi <notifications@github.com>
Verzonden: maandag 16 september 2019 09:56
Aan: tmrowco/electricitymap-contrib <electricitymap-contrib@noreply.github.com>
CC: Visser BM, Martien <b.m.visser@pl.hanze.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [tmrowco/electricitymap-contrib] NL renewable power estimates (#1871)


I think you can go ahead with nuclear if we have enough evidence that the data is correct.
@MartienVisser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartienVisser&data=02%7C01%7Cb.m.visser%40pl.hanze.nl%7C62783f3f3bc54e39f19108d73a7b4a9b%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C1%7C637042173515299827&sdata=qFw6p5RpsD2zBTG68ae%2B52Y%2FpqOnlKsqMoGN02iZNhM%3D&reserved=0> , as you know much more than we do, are you able to tell us if the ENTSOE data is sufficiently correct?

Olivier

**Comment by PaulCornelissen** [comment]
There's still a bug. :-(

From ENTSOE:
![image](https://user-images.githubusercontent.com/5185181/65308914-597fde00-db8b-11e9-9efa-d3bfffda4ae8.png)
9622MW load at 1:30 UTC

From electricitymap 3:30 CET:
473MW nuclear + 9MW wind + 6.97GW unknown + 584MW import BE + 569MW import from NO - 701MW export to DK - 1.4GW export to DE = 6504MW load.

That's off by >-3GW.

ENTSOE @ 6:15 UTC:
12595MW load

From electricitymap 8:15 UTC:
472MW nuclear + 39MW wind + 101MW solar + 11900MW unknown + 1400MW import BE + 730MW import NO - 909MW export DE - 113MW export UK = 13620MW load.

That's off by >+1GW.

I've found one bug:
```
    # We want to know the net-imports into NL, so if NL is in zone_1 we need
    # to flip the direction of the flow. E.g. 100MW for NL->DE means 100MW
    # export to DE and needs to become -100MW for import to NL.
    for e in exchanges:
        e['NL_import'] = e['netFlow'] if zone_1 == 'NL' else -1 * e['netFlow']
```

`zone_1` isn't assigned in the loop. In the current version it's hard at the value "DK-DK1", so all exchanges get their sign flipped.

I changed it to this:
```
    for e in exchanges:
        if(e['sortedZoneKeys'].startswith('NL->')):
            e['NL_import'] = -1 * e['netFlow']
        else: 
            e['NL_import'] = e['netFlow']
```
That makes it better, but still it's not completely explainable. I've looked at it with some debug output and the exchange values seem to be of the right sign. I've taken the output from the net-import calculation and looked at the electricity map and did the calculation manually for some time stamps:
```
Current:
                           NL_import  Manual calculation
datetime                                       
2019-09-19 15:00:00+00:00  -459.3201
2019-09-19 16:00:00+00:00  -194.2961
2019-09-19 17:00:00+00:00  -436.3486  -150
2019-09-19 18:00:00+00:00  -305.3416  -278
2019-09-19 19:00:00+00:00  -318.4136
2019-09-19 20:00:00+00:00 -1088.1826
2019-09-19 21:00:00+00:00 -1462.1841 -1444
2019-09-19 22:00:00+00:00  -919.4425
2019-09-19 23:00:00+00:00  -818.5121
2019-09-20 00:00:00+00:00  -829.0985
2019-09-20 01:00:00+00:00  -864.4914  -787
2019-09-20 02:00:00+00:00  -965.1298
2019-09-20 03:00:00+00:00  -752.3949
2019-09-20 04:00:00+00:00  -378.0595  -381
2019-09-20 05:00:00+00:00   849.1985
2019-09-20 06:00:00+00:00  1338.9795  1370
2019-09-20 07:00:00+00:00  1600.5969   831
2019-09-20 08:00:00+00:00     6.6490
2019-09-20 08:00:00+00:00   -33.5430   688
2019-09-20 09:00:00+00:00   636.0520
2019-09-20 10:00:00+00:00  -410.1680
```

I wouldn't mind if were only off by ~50MW or so. That would be explainable by different sampling times of the exchanges during ramping, but a difference of ~800MW is significant enough that I'm wondering what's causing it?

If anyone feels tempted to have a look what's causing the residual difference, please do.

**Comment by joppiesaus** [comment]
Currently, for the Netherlands, you do not see solar power at the electricity map, but according to http://energieopwek.nl/ there is definitely solar power being generated(including self-consumption). I think there's something wrong with the ENTSOE data source, it gives out 0 for solar electricity while there's in fact solar electricity present.

I don't see an easy way to fix this but I wanted to share this information.

**Comment by PaulCornelissen** [comment]
Yes, that seems correct. Also wind seems to be low. I also noticed that
total generation + imports is lower than entsoe consumption numbers. So
clearly there's something missing.

My hypothesis is that Tennet only reports numbers for generators feeding
into the main transmission grid and not into the distribution grid. NL has
many small CHP gasplants that feed the distribution grid. Solar is all
distributed. Large portion of onshore wind also feeds into distribution
grid. Or maybe there's a capacity threshold something like >100MW or so.

**Comment by corradio** [comment]
Hi all,
Is this issue still happening with the ENTSOE data? Else it would probably be good to reach out to them so they are aware of it.
Olivier

**Comment by Salix-Knot** [comment]
FYI Martien Visser on Twitter: average CO2 is 380 gr/kWh in 2019.

https://twitter.com/BM_Visser/status/1216985364457500673

**Comment by corradio** [comment]
@PaulCornelissen I believe this issue can be closed?

**Comment by PaulCornelissen** [comment]
Yes. NL data quality is still sub-par, but we can best track that in #78.

**Comment by corradio** [comment]
Perfect, thank you all for your efforts, and merry christmas 🎄
