### ISSUE TITLE
Toggle consumption / production looks weird at open

### ISSUE THREAD

**Issue by martincollignon** [tmrowco/electricitymap-contrib#1969]
Mac / Chrome. This is how the toggle looks like to me. Clicking on it makes it normal again.
<img width="304" alt="Screenshot 2019-09-24 at 10 21 22" src="https://user-images.githubusercontent.com/2604526/65494491-3e77db80-deb5-11e9-87cf-3fdfe1b15c43.png">

**Comment by corradio** [comment]
@ovbm are you able to help? Maybe it's related to your last PR?

**Comment by ovbm** [comment]
Can't reproduce on Firefox & Chrome. Could reproduce on Safari, on every other refresh O.o. No js errors.

**Comment by Chopinsky** [comment]
I can reproduce this issue on my Chrome as well. I think the issue comes from the first-load, on any ensuing refreshes or reloads, the toggle button works just as expected. The problem seems to come from the code @jamescrowley has mentioned: the overlay's `left` and `width` properties are miscalculated on the first run.  

I'd like to work on this issue, it shouldn't be too complex imho, but if anyone could point me to where the first-load logic lives, that would be of great help!
