### ISSUE TITLE
Data for region Estonia

### ISSUE THREAD

**Issue by petrk94** [tmrowco/electricitymap-contrib#2083]
Hello,

I got in contact with the regenerative energy association of estonia and they provided me the following link with a dashboard to the wind power plants, maybe you can work with it:

https://dashboard.elering.ee/en/system/production-renewable

**Comment by jarek** [comment]
Hello,

We have data for Estonia, including wind:

![image](https://user-images.githubusercontent.com/47415/68169788-69852e80-ff3b-11e9-8bfb-ad2720cde99f.png)

This matches current output of https://dashboard.elering.ee/en/system/production-renewable (I'm seeing 229 MW right now) fairly well.

Perhaps Estonia's data was temporarily offline when you looked?

**Comment by petrk94** [comment]
Hi @jarek ,
ah okay, no, it didnt was offline, I just wondered, that the production caused the highest amount of CO2 in europe, what I thought didnt could make sense, if the regenerative energy association has that amount of wind power.
See my screenshot

![estonia](https://user-images.githubusercontent.com/19719052/68188554-b1db3580-ffa9-11e9-9b35-54053023ca8e.PNG)

**Comment by jarek** [comment]
It is because the "coal" burned in Estonia is unfortunately incredibly CO2eq-emitting oil shale, see https://en.wikipedia.org/wiki/Oil_shale_in_Estonia#Air_emissions

(And to an extent the emitters rank is because the Estonian shale has a region-specific CO2eq value for it, while other dirty sources like brown coal / lignite don't yet - that's planned in #738)

**Comment by alixunderplatz** [comment]
I think nothing can be added to Estonia as it is, so I will close this issue.
#1015 has a summary of alternative websites / data sources for europe including Baltic states already.
