### ISSUE TITLE
Time stamp of data

### ISSUE THREAD

**Issue by pandorarex** [tmrowco/electricitymap-contrib#2130]
When looking at OpenNEW:South Australia from opennem.org.au the data shows at 13:10, 26/12/19 that the current Renewable Energy Contribution is 70.7%. When looking at electricityMap it only shows 23% Renewable. I do know that the OpenNEW website is correct. Is there a explanation for this rather large difference in numbers? Thanks Rex

**Comment by corradio** [comment]
Indeed the data source we use should be updated, see https://github.com/tmrowco/electricitymap-contrib/issues/1196.
Are you able to help? Will close this issue in favour of the other

**Comment by jarek** [comment]
Right now Electricity Map is showing 42% renewable while OpenNEM shows 40% renewable, so we're not off all the time.

For sake of future debugging, here is data I've found:

OpenNEM website seems to be showing me data timestamped in UTC, judging by solar production peaking around midnight. At 2019-12-26T00:05:00Z which I as far I can tell is around the time mentioned by @pandorarex, OpenNEM was showing ~730 MW rooftop solar, ~225 MW utility solar, 373 MW wind, around 320 MW gas, and 498 MW imports:

![Screenshot_2019-12-29_18-05-54](https://user-images.githubusercontent.com/47415/71563931-15438a00-2a66-11ea-92ec-75026f4203d6.png)

Whereas at 2019-12-26T00:00:00Z (5 minutes earlier, sorry), Electricity Map had 289 MW solar, 315 MW wind, 270 MW gas, and 122 MW imports (the timestamp in the screenshot is in UTC-5):

![Screenshot_2019-12-29_18-08-08-crop](https://user-images.githubusercontent.com/47415/71563949-4cb23680-2a66-11ea-9b43-2ca161370eba.png)

The numbers are indeed off, though we'd need a better check of Electricity Map history to determine what the exact problems where (which might not be worth it since we know the whole thing is bugged anyhow). A big discrepancy is solar, and that's likely because rooftop solar estimate comes from a different source and loading that failed - that's unfortunately a known problem as seen in #799. The overall Australian issue #1196 should indeed help here.
