### ISSUE TITLE
Data for Switzerland

### ISSUE THREAD

**Issue by jermannmartin** [tmrowco/electricitymap-contrib#2138]
Can any one help to include also the data for Switzerland?

**Comment by alixunderplatz** [comment]
Hi @jermannmartin and welcome :)
Please see issue #892 where the data problems for Switzerland are discussed.
The data which is published on ENTSO-E is incomplete at the moment, which is the reason why Switzerland is "grey" on the map. You can select the country on the map and will see all the data we have. Seems like there is nothing we can do to get the desired data to fill the gap between what is reported and what is actually produced.
I'm closing your issue because it is a duplicate. Feel free to comment in #892 if you have found any other sources.
