### ISSUE TITLE
Chicago is in PJM, not MISO

### ISSUE THREAD

**Issue by notnami** [tmrowco/electricitymap-contrib#2177]
Currently, ElectricityMap lists all of Illinois as being part of MISO. However, Illinois has two major electric utilities — ComEd and Ameren. Ameren is indeed part of MISO, but Chicago and most of northern Illinois is served by ComEd, which is part of PJM ([see PJM map here](https://www.pjm.com/library/maps/lmp-map.aspx)). 

This almost certainly affects the CO2eq numbers reported by ElectricityMap. Most environment/energy nerds in Illinois know that ComEd’s electricity has a smaller carbon footprint than Ameren’s. Ameren/MISO still supply a lot of power from coal, whereas ComEd/PJM generally use less coal and more low-carbon sources such as nuclear and hydro. 

So, if possible, the maps for MISO and PJM should be updated.

**Comment by robertahunt** [comment]
Thanks notnami! I believe that even if the borders of the MISO/PJM grids on the frontend are incorrect, the data for MISO and PJM is correct. Unfortunately I think we have had issues in the past finding accurate geojson information for the different US areas (ref: #143 ). If you can find a new geojson datasource, that would be excellent! Otherwise, we will continue to keep an eye out for improved data for this!

**Comment by robertahunt** [comment]
Ah, touche. No, unfortunately. However, if you make an API call specifying the zone, such as curl 'https://api.co2signal.com/v1/latest?countryCode=US-MISO' -H 'auth-token: myauthtoken', you will get the data for US-MISO which will not include chicago. However, until we can get more accurate geojson data, I see no way to improve this.

**Comment by robertahunt** [comment]
Closing this, we are tackling it in #143
