### ISSUE TITLE
Kosovo / Serbia border

### ISSUE THREAD

**Issue by socraton** [tmrowco/electricitymap-contrib#2184]
Hi,

Please add Kosovo to your map; today only Serbia shows. USA and most western allies recognize Kosovo (with its 95% albanians), while Russia/China/Serbia and allies does not.

Read more: https://en.wikipedia.org/wiki/International_recognition_of_Kosovo

A compromise could be a dotted line.

**Comment by robertahunt** [comment]
Hi Socraton. 
On our map we try to focus on getting as low of a geographical granularity as possible to best communicate CO2 emissions, so we would be happy to put Kosovo as a separate region. In this case however, I cannot find a separate datasource for live electricity production (separated by fuel source) in Kosovo and I strongly suspect it is included in the 'Serbia' production data we have, which is why these two regions are merged. If I am wrong on that, and the Serbian production data excludes Kosovo, or if you can find a new datasource for electricity generation in Kosovo, we can revisit this. For now I am going to close this issue. 
Thanks!
Roberta
