### ISSUE TITLE
US-SPP: Parser works in local testing but map is blank

### ISSUE THREAD

**Issue by jesserizzo** [tmrowco/electricitymap-contrib#2201]
For US-SPP, when I clone the repo and run the parser test script, it pulls the data successfully. But the map shows this area as blank.

The parser is returning an array of objects like this:

```
{
    'zoneKey': 'US-SPP', 
    'datetime': datetime.datetime(2020, 2, 9, 1, 40, tzinfo=<UTC>), 
    'production': {
        'coal': 5957.8, 
        'oil': 0.0, 
        'hydro': 1424.6, 
        'gas': 4200.4,
        'nuclear': 2031.7, 
        'solar': 0.0, 
        'biomass': 12.7, 
        'wind': 16967.4, 
        'unknown': 33.0
    },
     'storage': {}, 
     'source': 'spp.org'
}
```

**Comment by systemcatch** [comment]
The parser test script won't update the map, try running the command [listed here](https://github.com/tmrowco/electricitymap-contrib#update-the-map) which will work.

**Comment by jarek** [comment]
I think what is meant here is that the Electricitymap.org website doesn't show any recent data for SPP?

Checking our logs https://kibana.electricitymap.org/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:spp),sort:!('@timestamp',desc))

In there, I see messages like `Datetime 2020-02-12 03:15:00 requires a timezone` but that's strange since the value posted above has a timezone?

There are also some exception stacks like:

```
  File "/home/contrib/parsers/US_SPP.py", line 306, in fetch_wind_solar_forecasts
    raw_data = get_data(FORECAST_URL)
  File "/home/contrib/parsers/US_SPP.py", line 41, in get_data
    df = pd.read_csv(StringIO(req.text))
... pandas files ...
  File "pandas/_libs/parsers.pyx", line 2112, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 8, saw 2
```

**Comment by systemcatch** [comment]
@jarek yeah you're right, I misinterpreted what was said.

pandas uses pytz internally for dealing with timezones, I wonder if that is throwing things off.

**Comment by corradio** [comment]
I',m on it.
