### ISSUE TITLE
UK data: Drax dashboard

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#2204]
This was shared in Slack by ABerrow. I don't have much time to compare with our existing data source bmreports.com, so just pasting this here so it doesn't get forgotten:

> https://electricinsights.co.uk/#/dashboard?&_k=c104wq 
> This website might be useful for uk. Came from a tweet from Drax, a company that runs a coal plant in the uk so might be the real deal for data rather than estimates 

on the "Methodology and Sources" it says:
> The Electric Insights website and quarterly reports use free and public data that is sourced from National Grid (Britain’s system operator), Elexon (who run the wholesale electricity market) and Sheffield Solar (who estimate the power output from the country's 1 million solar panels). The methodology for acquiring, processing and presenting data has been written up as an academic paper. It is published in the journal Energy Policy and is available to read for free here.

**Comment by systemcatch** [comment]
Interesting, for context Drax was (maybe is still?) the single largest thermal power plant in the UK at ~4GW. It used to run entirely on coal but has now been partly converted to use biomass, I think there are plans to convert the remaining units to gas.

**Comment by robertahunt** [comment]
Nice! Thanks jarek. I also don't have time to dive into switching datasources now, but in case it is useful in the future: 
Elexon is the company behind bmreports, and the source of most of the data in the UK, so I think Drax's main source of data is the same as ours. I am going to guess they use Elexon for most of the data, then probably use National Grid for the emissions data, and it looks like Sheffield Solar predicts much higher solar production than Elexon accounts for (yesterday Elexon peaked at 1.5 GW and Sheffield Solar peaked at 2.81) (probably accounting for behind the meter production). I think the main outcome of this could be to supplement Elexon's data with better solar data - this isn't something we can do in our current system, but I'd like to adapt it to allow for multiple data sources in the future.

**Comment by AyrtonB** [comment]
@systemcatch The remaining units are going to be converted to biomass as well but they're also looking at building 4 new gas turbines although they may try and reduce the footprint with CCS (they currently have a 1t/day pilot).

@robertahunt They don't use NG for the emissions data, instead they apply carbon intensity factors to the different fuel types they have. Sheffield Solar also includes estimates for embedded solar generation rather than just transmission level, they also provide regional forecasts through their API. 

One thing to be wary of with the EI API though is that the separate forecasts for on- and off-shore wind often have missing or incorrect data so I'd recommend just using the aggregate value which is correct. The same bug exists in BMRS and ENTSOE data.

**Comment by corradio** [comment]
I'll close this issue for now as it seems like we're using the same datasource. Feel free to re-open if I missed something!
