### ISSUE TITLE
New RESOURCE_TYPE : Wind Offshore

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2272]
Split `wind` into two items:
- `wind onshore`
- `wind offshore`

Pro:
- Wind Onshore and Offshore don't have same carbon impact.
- Some countries have a large production from wind farms offshore

Parsers ELEXON and ENTSOE and DK have data about Wind Onshore:
https://github.com/tmrowco/electricitymap-contrib/search?q=Offshore&unscoped_q=Offshore

**Comment by Manu1400** [comment]
https://windeurope.org/about-wind/daily-wind/hourly-generation 
This website give informations about DAY-1 wind onshore (and wind offshore) production in Europe, by country

**Comment by fbarl** [comment]
Interesting idea @Manu1400, thanks for a nice summary and the supporting links!

> Wind Onshore and Offshore don't have same carbon impact

I was wondering if we could find a link to the relevant research - if the difference is significant, that alone would be a good argument for making a split.

On the other hand, the question arises what to do with the parsers that don't make a distinction, i.e. would we categorize `wind` as `wind onshore` or `wind offshore` if the context is not provided? :thinking:

**Comment by fbarl** [comment]
cc @ahaselsteiner in case you'd like to to add your input ;)

**Comment by Manu1400** [comment]
In Europe, wind onshore in 2020 can be huge:

> 40 000 mégawatts éoliens off-shore d’ici 2020. Selon l’association européenne (EWEA), on comptera en 2020, 40 000 mégawatts (MW) éoliens off-shore installés au large des côtes européennes.
https://www.rte-france.com/fr/article/quand-l-energie-electrique-passe-sous-la-mer

Statistic in 2019:
> Europe now has 22.1 GW of offshore wind capacity
https://windeurope.org/about-wind/statistics/offshore/european-offshore-wind-industry-key-trends-statistics-2019/

**Comment by fbarl** [comment]
Sorry for not making myself more clear, what I meant is that it would be good to know if the difference in _carbon intensity_ was significant.

E.g. for most of the countries right now, the carbon intensity equals to _**11** gCO2eq / kWh_ for wind, and I wonder how much this number would differ between _wind onshore_ and _wind offshore_ :thinking:

![image](https://user-images.githubusercontent.com/1216874/76412729-6a6c1800-6394-11ea-8754-7c4a8a6f5925.png)

I'm no expert here, so I hope the question I'm asking makes sense :)

**Comment by ahaselsteiner** [comment]
Thanks for making me aware of this interesting project @fbarl .

I quickly searched for publications on the question of onshore vs offshore wind and stumbled upon this publication by Benou and others (2016): https://backend.orbit.dtu.dk/ws/files/129908950/Bonou_2016_Applied_Energy.pdf

In Table 4 they show the CO2/kWh for some selected onshore and offshore plants that they analyzed. The onshore plants had between 5 and 6 Climate Change g CO2-eq/kWh and the offshore plants had between 8 and 11 Climate Change g CO2-eq/kWh .

**Comment by corradio** [comment]
Hi @Manu1400 ,

We won't be able to split the mix (it would clutter the UI up too much), but the carbon intensity could be improved. This is currently covered by https://github.com/tmrowco/electricitymap-contrib/issues/738

**Comment by leonoverweel** [comment]
Hi @corradio, I was wondering what you think about this issue now, two years later?

My two cents I wanted to add:

1. If you look at this list, where for example hydro and hydro storage are already two separate categories, I don't think splitting wind into onshore and offshore would be a cause of significant extra clutter.
    <img width="447" alt="image" src="https://user-images.githubusercontent.com/7980521/170699047-e448f2be-7c20-414f-9edb-4747a9a2b3d8.png">

2. My day-to-day work is in short term power forecasting (wind, solar and demand, but with 90% focus on wind the past half year). In my world, onshore wind and offshore wind are really different beasts. This is mostly because capacities of offshore parks are 1-2 orders of magnitude above onshore parks. So operators invest in much more monitoring infrastructure offshore, and real-time data is much more commonly available for offshore parks than for onshore parks. This extends to the aggregates that grid operators make available to ENTSO-E. This difference in availability is a good argument for separating these IMO.

3. The above is especially true for The Netherlands. TenneT reports aggregated real-time 15-minute data to ENTSO-E for the offshore parks, which they meter directly. However, the vast majority of the (much smaller) onshore parks are not directly connected to the high voltage grid operated by TenneT, so the metering data is gathered by the local grid operators. I had a discussion with them about this on Twitter yesterday, and the conclusion is basically (in Dutch, sorry) that [they don't think it's worth the effort](https://twitter.com/JoostGreunsven/status/1529861192767922176) to get this real-time data from the local operators, aggregate it, and send it to ENTSO-E. So for NL, the offshore data is complete, while the onshore data is far from it. If these two categories weren't combined, it would be easier to deal with this and/or indicate it in the UI.

4. In the coming decades, a ton more offshore wind is being built -- [150 GW by BE, DE, DK and NL alone!](https://www.offshorewind.biz/2022/05/18/four-eu-countries-set-joint-target-of-150-gw-of-offshore-wind-by-2050/). These parks will be hooked up to each other and to "energy islands" which act in part as interconnects and in part as e.g. H2 production facilities. This will most likely have an effect on how this production is reported, so preparing your data model with a separate offshore category seems prudent.

Would love to know your thoughts!
