### ISSUE TITLE
Switching country panel to "emissions" doesn't change carbon intensity graph to emissions graph

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2300]
When switching to "emissions" in the country panel, the carbon intensity graph should change title and show the absolute emission per interval instead of the carbon intensity (just like the mix graph).

cc @fbarl 

![image](https://user-images.githubusercontent.com/1655848/77253894-e18b9100-6c5d-11ea-99d4-76cfc8fce5ca.png)

**Comment by fbarl** [comment]
@corradio Just to be clear, this functionality was never there before, right?

I'm asking because I first thought I might have accidentally removed this logic in https://github.com/tmrowco/electricitymap-contrib/pull/2254, but I can't dig up what you're describing anywhere in the code history.

If that's true, then we'll have to add a new new term in locales for the title - what do you think the title should be?

**Comment by corradio** [comment]
Heh you're right! I'm puzzled by this.
Let's introduce it then! Let's create a new key "emissions24h" with the text "Emissions in the last 24 hours".
