### ISSUE TITLE
speed up multi-language build

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2342]
The current webpack configuration builds the frontend once for each language, and that causes the build time to take an enormous amount of time (>15min), when a single build takes <1min.
It would be great if someone could help us optimise that!

**Comment by fbarl** [comment]
Thanks for opening this issue @corradio!

I actually wanted to ask this for a long time - what was the original motivation for configuring Webpack to have one build per language instead of having a single build that would import all the locales?

The bundle size difference shouldn't be significant and we could simplify _a lot_ of locales webpack logic if we moved to a single build (on top of improving the build time drastically).

**Comment by corradio** [comment]
The main reason was to reduce bundle size but I'm not sure it's worth it as you say
