### ISSUE TITLE
Double exchange arrows for some Canada - USA exchanges

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#2351]
Arrows for exchanges between US systems and Quebec, BC, and Alberta are showing double on the map. I'm guessing it's related to the US state split?

![quebec double arrows](https://user-images.githubusercontent.com/47415/78316226-27353d00-752d-11ea-9b92-5325c473bca5.png)

![bc ab double arrows](https://user-images.githubusercontent.com/47415/78316224-26041000-752d-11ea-88f5-7b52d80e5b25.png)

**Comment by robertahunt** [comment]
Hey!... This is a bit more complicated. This is because right now we are maintaining two versions of the US, so our customers have time to switch to the new US balancing authorities view/names. (you will notice in zones.json that we still have some of the old US zones).

I want to leave this issue open until that is fixed.

What is an immediate problem is that it looks like I made a mistake when inputting the direction of the exchanges (either the angle of the arrows, or the direction of the exchange). I'll look into this now.

**Comment by robertahunt** [comment]
Looks like it is the 'angle' of the US-Canada exchanges that is the problem. I'll make a PR.

**Comment by robertahunt** [comment]
Hmmm, but maybe I should remove the exchanges for the old US zones now, since either way the data will not be perfect.
