### ISSUE TITLE
Question Mark Appears Next To Generation Type Despite Capacity Data Defined

### ISSUE THREAD

**Issue by brandongalbraith** [tmrowco/electricitymap-contrib#2445]
It is my understanding that question marks should not appear next to generation types in the country panel when capacity information for the country has been defined in the zones.json config file. When reviewing generation mix data for Iceland (I have spot checked other country panels and the behavior appears consistent), the presentation deviates from expected behavior:

![image](https://user-images.githubusercontent.com/350893/80753640-363ee900-8af3-11ea-967b-b5fb990adfd7.png)

[Iceland zone.config](https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L2575-L2608)

Mentioned in [Slack](https://tmrow-team.slack.com/archives/CLEER5FQQ/p1587602754033900), @corradio suggested I create an issue for it.

**Comment by VIKTORVAV99** [comment]
I believe the question marks refer to current power generation and not installed capacity but I could be wrong.

**Comment by peterhughgriffin** [comment]
It seems that the installed capacity is 0, therefore the generation must be 0 too (except for wind).

`"capacity": {
      "biomass": 0,
      "coal": 0,
      "gas": 0,
      "geothermal": 753,
      "hydro": 2095,
      "nuclear": 0,
      "oil": 117,
      "solar": 0,
      "unknown": 0,
      "wind": 2`

I guess the parser is not defining them as 0 for live generation?

**Comment by peterhughgriffin** [comment]
Here's the output from the IS parser:

`{'zoneKey': 'IS', 'production': {'hydro': 1351.4587, 'geothermal': 638.4507, 'oil': 0.0}, 'storage': {}, 'source': 'amper.landsnet.is', 'datetime': datetime.datetime(2020, 5, 2, 21, 3, 20, 428469, tzinfo=tzutc())}`

The parser only looks for hydro, geothermal and oil data, because that's all that [the source](https://amper.landsnet.is/generation/api/Values) seems to give, no mention of the elusive 2MW of wind...

Either the parser needs to explicitly set the other values to zero (dangerous, as this is effectively storing some of the capacity information in two places) or the map needs to realise that zero capacity means known generation.

**Comment by VIKTORVAV99** [comment]
I believe the the map recognizing zero capacity and setting zero output should be the way to do this. Since that means no parser need to be hard-coded and changed whenever the capacity is updated.

On another but similar note maybe a exclamation mark should be added if production exceed the installed capacity?

**Comment by ajoga** [comment]
> Either the parser needs to explicitly set the other values to zero (dangerous, as this is effectively storing some of the capacity information in two places) or the map needs to realise that zero capacity means known generation.

Capacities can evolve with time as well as generation. Our knowledge of them, too.

I believe it's a good solution to store the capacity being at 0 in the zones file as well as the production being 0 in the parser. 

I suggest to modify the parser to output 0 where the capacity is zero

**Comment by robertahunt** [comment]
Unfortunately because the capacity is not always up to date, I don't want to introduce any hard rules around capping the production at the capacity - at the moment we use the capacity values for information only (to display to users), we don't use this to affect production because we know it is not 100% reliable. On the other hand, I am also reluctant to hard code production values into the parsers in case new plants are commissioned, or the parser is missing some production values. 

In my opinion the best solution is to solve this on the front end - if the capacity is 0 and we report no production, we should remove the question mark. @fbarl Do you think that would be doable?

**Comment by peterhughgriffin** [comment]
That sounds much more sensible.
I’ve not looked into the front end at all yet, but would be interested in looking into this

**Comment by robertahunt** [comment]
Awesome @peterhughgriffin , Let's see how hard @fbarl thinks it would be. He is by far the closest to the front end code and probably the best person to direct you with where to start. But feel free to do some digging yourself as well. It looks like the question mark is set in https://github.com/tmrowco/electricitymap-contrib/blob/90bb3e9b125a42e056df32f7afb9253b11ce9757/web/src/components/tooltips/countrypanelproductiontooltip.js#L80-L82 . And the main file for the production mix panel is https://github.com/tmrowco/electricitymap-contrib/blob/90bb3e9b125a42e056df32f7afb9253b11ce9757/web/src/components/countryhistorymixgraph.js 

(I think!)

**Comment by fbarl** [comment]
Hey thanks everyone for point this out!

> if the capacity is 0 and we report no production, we should remove the question mark

I agree - I opened #2501 where I address this issue by assuming the production is 0 if it's not explicitly given and the capacity is 0.

> In my opinion the best solution is to solve this on the front end

I did so but in a long run I think I'd prefer having this kind of logic on the backend as I see it as data sanitization :slightly_smiling_face:

**Comment by robertahunt** [comment]
Thanks! @fbarl I am not sure where we would put this logic in the back end though, but I agree doing calculations in the front end is not ideal.
