### ISSUE TITLE
Carbon intensity for Åland (AX) is sometimes missing

### ISSUE THREAD

**Issue by VIKTORVAV99** [tmrowco/electricitymap-contrib#2509]
Åland is not reporting any carbon intensity when there is no electricity production on the island and it's only importing from Sweden and Finland.
![image](https://user-images.githubusercontent.com/30777521/82142297-93e56c00-983b-11ea-9c81-101252e2374c.png)
Related issue: #2483

**Comment by corradio** [comment]
In this case the carbon intensity is missing although production is present

![image](https://user-images.githubusercontent.com/1655848/84160274-4640d580-aa6e-11ea-844d-2c5bab679ec2.png)

**Comment by corradio** [comment]
Also happens with South Island of NZ:

![image](https://user-images.githubusercontent.com/1655848/84744416-8397ec80-afb3-11ea-9876-bb6e449162ff.png)

**Comment by jarek** [comment]
Possibly because the other 1% is imported from Finland, it's just too small to show on the chart.

Screenshots taken right now, time is localized to UTC-4:

![sweden](https://user-images.githubusercontent.com/47415/84778439-fce21000-afb0-11ea-8353-76f3a76ba421.png)

![finland](https://user-images.githubusercontent.com/47415/84778434-fc497980-afb0-11ea-99ca-00b9018640ef.png)
