### ISSUE TITLE
Transmission arrows wrong arranged at first startup

### ISSUE THREAD

**Issue by Bohne13** [tmrowco/electricitymap-contrib#2532]
On **Chrome for Linux** an **Chrome for Android** the Arrows are not arranged correctly at first load. 
Chrome 83 latest stable release.
If i reload the page, everything is fine!

![2020-05-30_Screenshot ](https://user-images.githubusercontent.com/20006695/83338518-8a411700-a2c5-11ea-9886-dd7b8048e3e4.png)

**Comment by q--** [comment]
I've seem this in Firefox for Windows sometimes as well, not sure what causes it. Zooming in or out resolves it

**Comment by fbarl** [comment]
Thanks for reporting this @Bohne13!

This issue was most likely introduced by my map transition to React (#2395 / #2434) - I've also noticed it a few times but only when opening the debug console while the map would be loading (I guess it has to do with the viewport resizing then), so I didn't think of it as a high priority :thinking: 

I'll assign myself to it though as I touched that code last so would probably figure how to fix it quickly.
