### ISSUE TITLE
Circle jumps to the top of the price graph when the price is exactly zero

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2575]
GIF to show what I mean, this is for data for the Netherlands today

![Bug ElectricityMap electricity price circle jumps to top of graph when price is zero](https://user-images.githubusercontent.com/2470175/86580243-bdd72700-bf7e-11ea-9963-8e530290de03.gif)

**Comment by fbarl** [comment]
Good catch @q-- !

It seems like the issue is in https://github.com/tmrowco/electricitymap-contrib/blob/dcea10ddbebbc5dc9f7980ccc9bbb526f90db7d1/web/src/components/graph/graphhoverline.js#L20

Changing `datapoint[1]` to `isNumber(datapoint[1])` would probably fix the issue - I'll verify and open a PR during this week.
