### ISSUE TITLE
CountryTable should list all exchange zones that appear in historic graphs

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2591]
Currently the component `CountryTable` looks only at the zones that appear [at the focused timestamp](https://github.com/tmrowco/electricitymap-contrib/blob/aa523a67aa821b2005c7c94dc3cf55451c44c1c4/web/src/components/countrytable.js#L450). That can potentially cause the list to change its height and consequently the graphs to move and tooltips to flicker when hovering over the graphs at different timestamps.

This effect occurs much more often when looking at the historic period of 5 years instead of 24 hours - #2393.

The solution I propose here is to take a union of all the exchange zones that appear in the graphs across all the displayed timestamps to make sure the `CountryTable` never changes its height when hovering over the graphs.

**Comment by masquel** [comment]
I think fixed height for all data will not resolve this problem. You should think about better UI. For example, if you hover "Electricity prices in the last 24 hours" graph, you can't see CountryTable block in full height at all. Maybe you should move graphs to the top and add tabs to switch them.

**Comment by corradio** [comment]
One more info here:
I realised that changing the timestamp over the history graph causes the `prepareGraph` method of countryhistorymixgraph.js to be triggered, causing a recalculation of the whole graph, which of course makes the UI slower.
This is due to the fact that `prepareGraph` depends on `exchangeKeys` through `useCurrentZoneExchangeKeys`, which is changed everytime the timestamp changes.

The solution would be to make sure all graphs use a fixed `exchangeKeys` that doesn't change with timestamp. It would mean replacing
```javascript
const exchangeKeys = useCurrentZoneExchangeKeys();
```

with a calculation of exchangeKeys for *all*

Hope it makes sense and simplifies the fix.

**Comment by fbarl** [comment]
@masquel Thank you for your suggestion, I think you have a good point there! However, that would indeed require a bit more work on the UI and would probably lie outside of the scope of this issue. Would you be interested to open a [discussion](https://github.com/tmrowco/electricitymap-contrib/discussions) for it where you could lay out your suggestion in more details and perhaps provide some screenshots? :slightly_smiling_face: cc @Kongkille  

@corradio Thanks for the breakdown, this gives a much better action plan than what I wrote above :smile:
