### ISSUE TITLE
France carbon intensity for nuclear

### ISSUE THREAD

**Issue by OLIVIER-LUMINAIS** [tmrowco/electricitymap-contrib#2629]
Bonjour,

In France according to the IPCC, the quantity of CO² per Kwh is 8 grams of CO² equivalent / Kwh!

more now according to ADEM in France it is 6 grams of CO² / Kwh equivalent produced for French Civil nuclear electricity.

would it be possible to change the CO² produced by civilian nuclear power for France?

Extra information: https://www.youtube.com/watch?v=Bcg9yDp4Azs

to check this information go to 11 minutes and 27 seconds either there: https://youtu.be/Bcg9yDp4Azs?t=687

thank you.

**Comment by jarek** [comment]
Hello, thank you for the note!

Am I getting this right - looks like the source for the 6 gCOeq/kWh figure is https://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?conventionnel.htm which came in 2015 from https://eplca.jrc.ec.europa.eu/ELCD3/index.xhtml which has since been discontinued?

**Comment by jarek** [comment]
On a practical note, looks like reducing the French nuclear carbon intensity from the current IPCC 12 gCO2eq/kWh to 6 doesn't really make much of a change in overall carbon intensity right now. This is because most of the CO2eq emissions at the moment are anyway coming from the ~9% generated from natural gas.

Current figure is 73 gCO2eq/kWh, reducing nuclear to 6 would make the figure about 69 gCO2eq/kWh

![france](https://user-images.githubusercontent.com/47415/91500997-a6d3f780-e892-11ea-86de-e560f9e60bb2.png)
