### ISSUE TITLE
Overestimation of CO² emissions in France

### ISSUE THREAD

**Issue by LEMOINE-1955** [tmrowco/electricitymap-contrib#2636]
Hi,

[GHG Emissions in French Nuclear Plants.docx](https://github.com/tmrowco/electricitymap-contrib/files/5149835/GHG.Emissions.in.French.Nuclear.Plants.docx)
You will find attached a complete study that explains the reasons why using the IPCC figure (which is a median of the emissions of nuclear power plants worldwide) is equivalent to doubling the carbon footprint of nuclear power plants in France.

**Comment by Kongkille** [comment]
Hi, thanks for the article!

Using IPCC-alternatives per geography would be great. Currently it is not supported. Similar issues have been mentioned previously, it would be great if you could share this article in #738, so we can act on it.

I am going to close this issue, since it's a subset of the linked issue :)

**Comment by jarek** [comment]
see also https://github.com/tmrowco/electricitymap-contrib/issues/2629 for the nuclear number specifically. it doesn't make that much of a difference overall as long as you have any other source of generation running
