### ISSUE TITLE
Wrong carbon intensity for cross-border tooltip

### ISSUE THREAD

**Issue by GitMatze** [tmrowco/electricitymap-contrib#2700]
Probably due to power being zero..

![TooltipError](https://user-images.githubusercontent.com/45139485/94737383-09c31d80-036e-11eb-9f8f-dc038f4b77d5.png)

**Comment by corradio** [comment]
This is due to a discrepancy between the two conditions
https://github.com/tmrowco/electricitymap-contrib/blob/52db4e03fac4ee5d85b59b08754899b4418bf37e/web/src/helpers/zonedata.js#L41
and https://github.com/tmrowco/electricitymap-contrib/blob/master/web/src/components/tooltips/countrypanelexchangetooltip.js#L35

**Comment by GitMatze** [comment]
@corradio Seems to be still wrong

**Comment by corradio** [comment]
@GitMatze can you post a screenshot?

**Comment by GitMatze** [comment]
![image](https://user-images.githubusercontent.com/45139485/104908050-31261080-5986-11eb-977a-e04f1528aff7.png)

**Comment by corradio** [comment]
What would you see as the expected behaviour?

**Comment by GitMatze** [comment]
I think the last line in the tooltip is wrong. It says the carbon intensity of Southwest Norway is 383 g/kwh, but  that's the carbon intensity of Germany.

**Comment by corradio** [comment]
Indeed that's a bug! Thanks for following up
