### ISSUE TITLE
Alegro exchange between Germany and Belgium reporting 0 MW in ENTSOE

### ISSUE THREAD

**Issue by faehre74** [tmrowco/electricitymap-contrib#2794]
Germany (Amprion) has a new interconnector link to Belgium (Elia).

**Comment by mouse256** [comment]
Some more info:
https://www.amprion.net/Grid-expansion/Our-Projects/ALEGrO/

Data is available already on ENTSOE:
https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=GRAPH&areaType=BORDER_CTY&atch=false&dateTime.dateTime=06.11.2020+00:00|CET|DAY&border.values=CTY|10YBE----------2!CTY_CTY|10YBE----------2_CTY_CTY|10Y1001A1001A83F&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by ssmssam** [comment]
I'd be happy to take this on. Is there a guide for adding interconnectors?

I know IFA2 is due to come online around the end of year too, between GB and France.

**Comment by ssmssam** [comment]
From what I can see, it would involve changing the README, config/exchanges.json and parsers/ENTSOE.py . Is that correct?

**Comment by jarek** [comment]
This was previously discussed in https://github.com/tmrowco/electricitymap-contrib/issues/2723 and should have been added in https://github.com/tmrowco/electricitymap-contrib/pull/2774

In fact if you look at the region details, the exchange is already there:

![bede](https://user-images.githubusercontent.com/47415/98755407-76323300-2396-11eb-87f9-2831c0de3fc7.png)

However in the past 24 hours it's always showing 0.

Also, the exchange arrow is not showing up on the map. This might be because of the 0 detected transfer, or because the front-end of the map has not been redeployed recently - not sure.

**Comment by jarek** [comment]
In fact it looks like Electricity Map shows archive data well, e.g. for November 5, 00:00 UTC (screenshot is in UTC-5, this is from an internal tool to view older data):

![be-de-nov-4](https://user-images.githubusercontent.com/47415/98755963-94e4f980-2397-11eb-88c1-c994f7cefd58.png)

So this seems to be case of either no energy actually being exchanged, or missing data in ENTSOE?

**Comment by Fred-3000** [comment]
Alegro simply isn’t in commercial service yet.

**Comment by PaulCornelissen** [comment]
![image](https://user-images.githubusercontent.com/5185181/99548368-dccbd800-29b8-11eb-9e00-08cbab34fe0a.png)

Today they're transferring some power. I've seen it at 1GW before. Probably only when they are testing. Unless we see that it's not being displayed when there is data in ENTSOE.

I propose to close this issue as it seems to work.

**Comment by Fred-3000** [comment]
Yep, the parser is working fine. 
According to Elia commercial operation started today, with a capacity of up to 100 MW, perfectly matching Electricitymap's data. 
https://twitter.com/eliacorporate/status/1329055358208397312

**Comment by jarek** [comment]
Okay, thanks for confirmations! I'll close the issue but feel free to reopen if it seems like it's not working again.
