### ISSUE TITLE
Over estimation of NL CO2/kWh emissions due to high unknown CO2 emission factor

### ISSUE THREAD

**Issue by mhooi** [tmrowco/electricitymap-contrib#2804]
I was wondering what the reasoning is for the assumed output of 700 g CO2eq/kWh for the part of electricity consumption where the source is unknown. 

![elecmap](https://user-images.githubusercontent.com/65292771/99391345-5e990400-28da-11eb-8066-2b1b944aa239.png)

We know that the power generation from Coal fired power plants is very limited these days and is reported separately and quite accurate I think. So the unknown part in the Netherlands could be generated by Gas  (490 g CO2eq/kWh) or by even lower CO2 emitting sources.    [https://pbs.twimg.com/media/EnAsK0-XcAA1IUY?format=jpg&name=900x900](url)

For other countries this doesn't really matter but the Netherlands has often a fair bit of "unknown" (20-30%) so the total CO2 emission per kWh is overestimated by a fair amount! 

What the best value for the unknown part should be, I don't really know. By my opnion a max value of 490 should be reasonable. 

Maybe @MartienVisser or @PaulCornelissen  can comment?

**Comment by q--** [comment]
Here is data from the [Dutch statistics office](https://opendata.cbs.nl/statline/#/CBS/en/dataset/84575ENG/table?ts=1605622623305) on electricity production by fuel source. Perhaps it's possible to compare this with ENTSO-E data to infer what the composition of the "unknown" generation is.

**Comment by mhooi** [comment]
> Here is data from the [Dutch statistics office](https://opendata.cbs.nl/statline/#/CBS/en/dataset/84575ENG/table?ts=1605622623305) on electricity production by fuel source. Perhaps it's possible to compare this with ENTSO-E data to infer what the composition of the "unknown" generation is.

This check has been done before I think. The reason the Netherlands has a fair amount of "unknown" is for example due to lot's of decentralized electricity generation in greenhouses and other local consumers. 

So the estimation of the amount of "Unknown" is not the question, more the guestimate of the source of this electricity. Now is has an assumed coal base source while in reality it is probably Gas based.

**Comment by q--** [comment]
I know. What I'm proposing is taking total generation by type for e.g. 2017 from the CBS, subtracting the generation by type accounted for in ENTSO-E data for that year so that the remainder of the generation will be the composition of the "unknown" generation in ENTSO-E.

For example, say the CBS has 69,976 TWh of gas generation for 2019 and ENTSO-E has 12,345 TWh. Now we know that the "unknown" portion in the ENTSO-E data for that year the remaining 57.631 TWh of gas generation.

**Comment by PaulCornelissen** [comment]
@mhooi @q-- I agree that the unknown part is to high and that we should estimate a better CO2 intensity. 

The CO2 intensity of gas is probably also to high for NL, because NL uses mainly modern CCGT and very few open cycle gasturbines. Many CCGT also run as CHP plant. Then there's a lot of gas engine CHP plants mostly/all reported as unknown. 

The other parts of unknown are:
* waste incineration (NL is a waste importer, we overbuild waste incinerators because increasing recycling rates weren't properly accounted for).
* blast furnace gas (fromt TATA steel in IJmuiden)
* biomass (but it is fairly sure that a large part of biomass generation is counted as coal, because it is co-fired in coal plants and not reported separately to ENTSOE.*)
* negligible amount of hydro

\* This is especially true for the Amercentrale which is a "coal" CHP plant that delivers 600MWe/350MWth and that was planned to increase from 10% woodgas/40% woodpellets in 2016 to 80% woodpellets/10% woodgas by this year. Not sure if that has been achieved yet, but it's basically running as baseload powerplant because of the heat output that's required and maybe also because of subsidies on biomass. Fairly sure this plant which probably runs 90% on biomass is reported as coal.

NL data is a mess unfortunately. Maybe it's best to just assume 490 gCO2 for the time being as a intermediate fix and then see if we can come to a better understanding of what's really happening?

**Comment by mhooi** [comment]
I agree with you Paul, assuming a 490gCO2/kWh is a first good guestimate. At least a better one compared to the current one of 700. 

How can we proceed with this? I'm not such a data nerd that I can do these changes by myself unfortunately.

**Comment by PaulCornelissen** [comment]
@mhooi something like ^^that commit should do.

**Comment by mhooi** [comment]
Wow, really great. Let's see when this is updated in the dashboard. 

Maybe we can fine tune the assumptions a bit more in the future with the help of @MartienVisser, the unknown part and maybe also the Gas part because of the reasoning you gave above.

**Comment by q--** [comment]
> biomass (but it is fairly sure that a large part of biomass generation is counted as coal, because it is co-fired in coal plants and not reported separately to ENTSOE.*)

[Here's the portion of the biomass that's co-firing with coal](https://longreads.cbs.nl/hernieuwbare-energie-in-nederland-2019/biomassa/#meestoken-van-biomassa-in-elektriciteitscentrales). We can subtract that from the total biomass in the annual generation mix I linked earlier to derive the portion of "unknown" that's biomass.

**Comment by mhooi** [comment]
> @mhooi something like ^^that commit should do.

Do we know when and how this commit will be merged with the master?

**Comment by mhooi** [comment]
@FelixDQ, could you elaborate how to merge this proposed fix?

**Comment by PaulCornelissen** [comment]
@mhooi the challenge is not in merging the change, but calculating a best estimate.

@q-- 
> I know. What I'm proposing is taking total generation by type for e.g. 2017 from the CBS, subtracting the generation by type accounted for in ENTSO-E data for that year so that the remainder of the generation will be the composition of the "unknown" generation in ENTSO-E.
>
> For example, say the CBS has 69,976 TWh of gas generation for 2019 and ENTSO-E has 12,345 TWh. Now we know that the "unknown" portion in the ENTSO-E data for that year the remaining 57.631 TWh of gas generation.

When I download the ENTSO-E transparency data for 2019 I get to 50,342TWh of Fossil Gas generation instead of the 12,345TWh you mention:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/5185181/103092726-79a51500-45f8-11eb-8390-fb8748d379e8.png">
Is that the difference between real-time reported gas and back-filled reporting in ENTSOE data?

Waste and Biomass in ENTSOE data seem to be ~1 month behind. So for 2019 we have some but for real-time we can assume these to be always zero.

Looking at the production per Unit in ENTSOE we see that the Amer 9 unit (coal, but with up to 90% biomass co-firing) is reported as coal and that IJmond (blastfurnace gas) is reported as other:
![image](https://user-images.githubusercontent.com/5185181/103093325-4794b280-45fa-11eb-8c1b-03843e36b45f.png)

From [CBS](https://longreads.cbs.nl/hernieuwbare-energie-in-nederland-2019/biomassa/#meestoken-van-biomassa-in-elektriciteitscentrales) we know in 2019 there was ~1.87TWh of biomass co-firing (gross) and 0.95TWh of decentralised electricity from biomass (gross)(mainly (de)construction wood-waste). Total ~2,72TWh.

From the [certificates of origin](http://www.certiq.nl/fileadmin/user_upload/Statistisch_overzicht_2020/2020-11_november_NL.pdf) (COO) issued in NL we know the 12month rolling average for Biomass to be 1,711TWh (first page, first table).

So we know from that, that biomass has not increased. Maybe decreased, but we don't know what percentage the CBS bases on COO's and what percentage on the inquiries it sends out...

We do know that the 1,87TWh of co-firing very likely reported as coal. That's an annual average of 213MW.

From the [CBS data for 2019](https://opendata.cbs.nl/statline/#/CBS/en/dataset/84575ENG/table?dl=45964) we know the actual numbers. By comparing that with the ENTSOE data for 2019 (see screenshot above) we can figure out how much of what was underreported:
Biomass: ~5TWh
Fossil gas: ~18.8TWh
Hard Coal: negligible 
Nuclear: negligible
Solar: negligible (because we get is from energieopwek.nl)
Wind: negligible (because we get is from energieopwek.nl)
Waste (non-renewable part): 1.6TWh
Oil products: 1.385TWh
Hydro power: 0.074TWh
Other: 0.493

<img width="514" alt="image" src="https://user-images.githubusercontent.com/5185181/103103313-82114600-4620-11eb-812a-3acd928793fd.png">
So after weighting I come to 468gr/kWh.

What do you think?

**Comment by q--** [comment]
> When I download the ENTSO-E transparency data for 2019 I get to 50,342TWh of Fossil Gas generation instead of the 12,345TWh you mention:

Yes, those numbers were meant as a hypothetical example. [_Say_ can also mean _imagine_](https://dictionary.cambridge.org/dictionary/english/say#cacd-1-3)

I'll have a look at your calculations.

**Comment by q--** [comment]
Some nitpicks:

* Shouldn't we count blast furnace gas as 'coal' because that's were it originally came from?
* Given that the co-firing biomass is reported as coal, I assume you only counted the biomass that's not co-firing. Is that correct?
* > Solar: negligible (because we get is from energieopwek.nl)
  >Wind: negligible (because we get is from energieopwek.nl)
  
  The assumption here is that the wind and solar  not included in the ENTSO-E data only reaches the regional grid and therefore isn't part of the 'unknown' reported by TenneT to ENTSO-E, right? That would seem reasonable to me, but it does introduce a bit of uncertainty.

**Comment by PaulCornelissen** [comment]
Yeah, I know that meaning. However using 5 decimal places in your example suggests a level of accuracy that probably confused me.

* I don't think we should approach the counting of blast furnace gas semantically, but try to look at the actual CO2 emission it causes. Basically it's CO gas that's being burned to CO2 gas, so that must emit a lot of CO2. Also I expect the efficiency to be low, because it's a very lean gas. But from a marginal perspective it's probably close to zero, because it's a dangerous waste gas from steel making that needs to be burned to make it safe(ish), so if it wasn't used to generate electricity it'd be flared. So marginally it's probably close to zero. To make it even more complicated; it's also a CHP plant. So what percentage of the CO2 emissions that you do attribute to the power plant do you attribute to power generation and what percentage to heat?
I don't want to try to answer these questions, that's why I'm happy counting it as unknown.
* No, because that would increase the error. We are counting biomass as coal now. 
* For NL unknown is the greater of: ( ENTSOE_unknown ) and ( ENTSOE_reported_consumption - ENTSOE_gas - ENTSOE_coal - ENTSOE_nuclear - Energieopwek.nl_solar - Energieopwek.nl_wind - net_imports )
So actually unknown is too low by however much power doesn't reach the TSO grid in the situation that ENTSOE_unknown is the smaller value.

In general the CO2 intensity calculated by electricitymap is way to high for NL. This morning Martien Visser reported his calculated [average CO2 intensity for NL electricity generation at 305grCO2eq/kWh](https://twitter.com/BM_Visser/status/1344943758173995008). But that won't be fixed until we do something like start using the ecoinvent country specific numbers #738.

**Comment by mhooi** [comment]
> @mhooi the challenge is not in merging the change, but calculating a best estimate.
> 
> @q--
> 
> > I know. What I'm proposing is taking total generation by type for e.g. 2017 from the CBS, subtracting the generation by type accounted for in ENTSO-E data for that year so that the remainder of the generation will be the composition of the "unknown" generation in ENTSO-E.
> > For example, say the CBS has 69,976 TWh of gas generation for 2019 and ENTSO-E has 12,345 TWh. Now we know that the "unknown" portion in the ENTSO-E data for that year the remaining 57.631 TWh of gas generation.
> 
> When I download the ENTSO-E transparency data for 2019 I get to 50,342TWh of Fossil Gas generation instead of the 12,345TWh you mention:
> <img alt="image" width="1138" src="https://user-images.githubusercontent.com/5185181/103092726-79a51500-45f8-11eb-8390-fb8748d379e8.png">
> Is that the difference between real-time reported gas and back-filled reporting in ENTSOE data?
> 
> Waste and Biomass in ENTSOE data seem to be ~1 month behind. So for 2019 we have some but for real-time we can assume these to be always zero.
> 
> Looking at the production per Unit in ENTSOE we see that the Amer 9 unit (coal, but with up to 90% biomass co-firing) is reported as coal and that IJmond (blastfurnace gas) is reported as other:
> ![image](https://user-images.githubusercontent.com/5185181/103093325-4794b280-45fa-11eb-8c1b-03843e36b45f.png)
> 
> From [CBS](https://longreads.cbs.nl/hernieuwbare-energie-in-nederland-2019/biomassa/#meestoken-van-biomassa-in-elektriciteitscentrales) we know in 2019 there was ~1.87TWh of biomass co-firing (gross) and 0.95TWh of decentralised electricity from biomass (gross)(mainly (de)construction wood-waste). Total ~2,72TWh.
> 
> From the [certificates of origin](http://www.certiq.nl/fileadmin/user_upload/Statistisch_overzicht_2020/2020-11_november_NL.pdf) (COO) issued in NL we know the 12month rolling average for Biomass to be 1,711TWh (first page, first table).
> 
> So we know from that, that biomass has not increased. Maybe decreased, but we don't know what percentage the CBS bases on COO's and what percentage on the inquiries it sends out...
> 
> We do know that the 1,87TWh of co-firing very likely reported as coal. That's an annual average of 213MW.
> 
> From the [CBS data for 2019](https://opendata.cbs.nl/statline/#/CBS/en/dataset/84575ENG/table?dl=45964) we know the actual numbers. By comparing that with the ENTSOE data for 2019 (see screenshot above) we can figure out how much of what was underreported:
> Biomass: ~5TWh
> Fossil gas: ~18.8TWh
> Hard Coal: negligible
> Nuclear: negligible
> Solar: negligible (because we get is from energieopwek.nl)
> Wind: negligible (because we get is from energieopwek.nl)
> Waste (non-renewable part): 1.6TWh
> Oil products: 1.385TWh
> Hydro power: 0.074TWh
> Other: 0.493
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/5185181/103103313-82114600-4620-11eb-812a-3acd928793fd.png">
> 
> So after weighting I come to 468gr/kWh.
> What do you think?

Great piece of work Paul, I'm impressed! 

Nice to see that the result is not that far off from the initial rough geusstimate of the 490 gr/kWh from gas.

**Comment by mhooi** [comment]
> Yeah, I know that meaning. However using 5 decimal places in your example suggests a level of accuracy that probably confused me.
> 
> * I don't think we should approach the counting of blast furnace gas semantically, but try to look at the actual CO2 emission it causes. Basically it's CO gas that's being burned to CO2 gas, so that must emit a lot of CO2. Also I expect the efficiency to be low, because it's a very lean gas. But from a marginal perspective it's probably close to zero, because it's a dangerous waste gas from steel making that needs to be burned to make it safe(ish), so if it wasn't used to generate electricity it'd be flared. So marginally it's probably close to zero. To make it even more complicated; it's also a CHP plant. So what percentage of the CO2 emissions that you do attribute to the power plant do you attribute to power generation and what percentage to heat?
>   I don't want to try to answer these questions, that's why I'm happy counting it as unknown.
> * No, because that would increase the error. We are counting biomass as coal now.
> * For NL unknown is the greater of: ( ENTSOE_unknown ) and ( ENTSOE_reported_consumption - ENTSOE_gas - ENTSOE_coal - ENTSOE_nuclear - Energieopwek.nl_solar - Energieopwek.nl_wind - net_imports )
>   So actually unknown is too low by however much power doesn't reach the TSO grid in the situation that ENTSOE_unknown is the smaller value.
> 
> In general the CO2 intensity calculated by electricitymap is way to high for NL. This morning Martien Visser reported his calculated [average CO2 intensity for NL electricity generation at 305grCO2eq/kWh](https://twitter.com/BM_Visser/status/1344943758173995008). But that won't be fixed until we do something like start using the ecoinvent country specific numbers #738.

About the Blast Furnace gas one can also argue that the CO2 emission is zero because it reusing a waste product, just like Biomass or Incin, but I don't think the official CO2 emission administration works like this for the BF gas. 
Apparently it may count as natural gas: [https://powerplants.vattenfall.com/velsen](url)
 

In the ETS emission data base one can look up the CO2 emissions for the Velsen power stations, if you know the produced amount of electrity you can do the math for the Blast furnace part. No coal is used in these plants.

**Comment by q--** [comment]
> No, because that would increase the error. We are counting biomass as coal now.

It probably would be better to override the coal carbon intensity for that instead IMO. Similar how the carbon intensity for "unknown" is overridden in e.g. [Russia](https://www.electricitymap.org/zone/RU-1?wind=true)

**Comment by PaulCornelissen** [comment]
@mhooi Good research! Only the IJmond plant is reported as other. The Velsen units are already reported as Fossil Gas:
![image](https://user-images.githubusercontent.com/5185181/103557256-329a0800-4eb3-11eb-8597-03d73b49f5cd.png)

It would require some scripting, because the per unit production can not be downloaded only per day. I don't really have time for that right now.

@q-- 
Yes that would be better. That's exactly what I was aiming at with this comment:

> In general the CO2 intensity calculated by electricitymap is way to high for NL. This morning Martien Visser reported his calculated average CO2 intensity for NL electricity generation at 305grCO2eq/kWh. **But that won't be fixed until we do something like start using the ecoinvent country specific numbers #738.**

I would very much like to have country specific emission factors for NL, but in the past such attempts have been blocked in favor of a unified approach that is the never ending story of #734... They even rolled back country specific factors that all ready were in there (#1400) even though there's a very good case to be made for country specific hydro CO2 intensities. Maybe @brunolajoie @corradio  @Kongkille would like to reconsider? Maybe there's a sliver of hope since Estonia still has a custom CO2 intensity for coal... 😉

**Comment by mhooi** [comment]
> @mhooi Good research! Only the IJmond plant is reported as other. The Velsen units are already reported as Fossil Gas:
> ![image](https://user-images.githubusercontent.com/5185181/103557256-329a0800-4eb3-11eb-8597-03d73b49f5cd.png)
> 
> It would require some scripting, because the per unit production can be downloaded per day only. I don't really have time for that right now.
> 

IJmond 01 is running only on fossil gas, before the corona I drove by every day so I'm pretty sure :p 

I don't think it is worth the effort to have this updated in another way, the accuracy will not improve that much and the effect is very marginal since not that much electricity is generated here.

**Comment by corradio** [comment]
Hi @PaulCornelissen ,
I believe it makes sense to add a different emission factor for "unknown". I'll happily review the PR.
We're trying to staff up the electricityMap team as we speak, so hopefully we'll be able to tackle emission factors in 2021.
I'm still ashamed we haven't gotten around to work on this before :(

Olivier

**Comment by mhooi** [comment]
> Hi @PaulCornelissen ,
> I believe it makes sense to add a different emission factor for "unknown". I'll happily review the PR.
> We're trying to staff up the electricityMap team as we speak, so hopefully we'll be able to tackle emission factors in 2021.
> I'm still ashamed we haven't gotten around to work on this before :(
> 
> Olivier

Thanks for the reply! Don't be ashamed, we all do our best to improve things over time. 

Maybe next we can have a look at Poland, there the CO2 emissions are heavily underestimated, electricity is coming mainly from lignite in Poland while the emissions are bases on coal (820 g/kWh). Looking at Estonia for example, the emission factor for coal is 1515 g/kWh. I think this approach would be also a better fit for Poland.
