### ISSUE TITLE
Calculate Swiss hydro storage CO2 intensity

### ISSUE THREAD

**Issue by PaulCornelissen** [tmrowco/electricitymap-contrib#2932]
Switzerland uses the global average CO2 intensity. But since #2931 Switzerland has a reliable CO2 estimation, so the infamous "Average by Tomorrow" needs to be calculated.

![image](https://user-images.githubusercontent.com/5185181/104817854-497e1a00-5824-11eb-97ee-04e54a7b3630.png)

**Comment by daviessm** [comment]
#2931 says that 150gCO2eq/hWh for hydro storage "is a guess".

**Comment by matthme** [comment]
Since #2898 is merged now, this issue should definitely be addressed since the currently used global average (300 g/kWh) is way too high. Since pumped storage makes up for a considerable fraction of Swiss electricity production and its global average is at the moment also used to calculate the emission factor of "unknown" it has substantial impact.

I don't know how you usually calculate the "Average by Tomorrow" but a method that I can propose which I used myself on historical CO2 data based on a slightly different approach than electricitymap's approach (only considering CH and it's neighboring countries, i.e. no "second order" CO2 flows from more remote countries) is the following:

1. Take pumped storage *consumption* of neighboring countries and calculate their hourly means for the year 2020 (they look very similar, for Switzerland itself it's unfortunately unavailable)

2. Normalize the resulting hourly means

3. Take the average of the normalized horly means and take them as the normalized Swiss pumped storage consumption profile --> "pumped_storage_consumption_CH_hourly_avg"

4. Calculate the average hourly profile of the CO2 intensity of Swiss electricity based on an guessed initial assumption for the pumped storage emission factor --> CO2_CH_hourly_avg

5. Multiply "pumped_storage_consumption_CH_hourly_avg" with "CO2_CH_hourly_avg" to get the mean CO2 intensity that the pumped storage plants "inhale"

6. Repeat step 4 with the new emission factor resulting from step 5 and iterate these steps until the result from step 5 converges

My result for 2020: 75 gCO2eq/kWh

This approach requires historical CO2 data of Switzerland which I don't know whether Tomorrow has it available (or can calculate it retrospectively). And the disadvantage of any constant emission factor obviously is that it is insensitive to seasonal fluctuations. In winter (large fossil imports from Germany) it is going to be too low and in summer it is going to be too high. But it is certainly more accurate than the global average used at the moment.

Here's a Jupyter notebook describing my approach:
[Pumped_storage_average_CH_2020.pdf](https://github.com/tmrowco/electricitymap-contrib/files/6334682/Pumped_storage_average_CH_2020.pdf)

**Comment by corradio** [comment]
For information, this is the place to add the information:
https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json#L211-L216
This is an example for another zone:
https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json#L74-L78
