### ISSUE TITLE
Wrong installed capacity for nuclear energy in Sweden 

### ISSUE THREAD

**Issue by swakter** [tmrowco/electricitymap-contrib#3119]
Installed capacity for nuclear energy in Sweden should be ~6.8 GW. Today it shows as 7.8 GW which means right now it says 87% capacity factor when it should be 100%.

Six reactors:
1400+1075+1130+990+1118+1172 = 6886 MW.

**Comment by madsnedergaard** [comment]
Hi @swakter, thanks for raising this!
I see that our numbers are indeed outdated, so I have changed it in this PR: https://github.com/tmrowco/electricitymap-contrib/pull/3120

I've also changed our data source to use [IAEA](https://pris.iaea.org/pris/CountryStatistics/CountryDetails.aspx?current=SE), so that's why the new number is a tiny bit off from yours :)
