### ISSUE TITLE
Potential data source for Sri Lanka

### ISSUE THREAD

**Issue by DeviousLab** [tmrowco/electricitymap-contrib#3179]
Hey guys!

I got recently introduced to your project by [JLooper](https://github.com/jlooper/carbon-trigger-extensionl), and I noticed several countries don't have data available yet and thought it'd be a great opportunity to contribute. The country I live in right now, UAE, does not have any real time data sources available to scrape unfortunately, only data up to 2019. 

So I tried looking up my home country, Sri Lanka. I found this [site](https://ceb.lk/electricity-generated/en) for the central board with a lot of statistics updated daily. I tried using the chrome devtools to monitor the network on the XHR tab to see where the source is but I couldn't find it. I was wondering whether this would be a viable source? Thanks!

**Comment by madsnedergaard** [comment]
Hi @DeviousLab, thanks for contributing! :)

We have an open issue for Sri Lanka here: https://github.com/tmrowco/electricitymap-contrib/issues/2936

As you can see, back then the problem was that data was slightly outdated - if you think this is no longer a blocking problem, it would be great if you can add a comment on that issue!

I'll close this issue so we keep information together in one place :)
