### ISSUE TITLE
Differences in Spain between REE/ENTSOE

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#3299]
Live data : 

https://demanda.ree.es/visiona/peninsula/demanda/tablas/2021-8-11/2
> 2021-08-11 03:10
> Solar fotovoltaica : 37 MW
> Solar térmica : 124 MW

versus https://www.electricitymap.org/zone/ES (same zone: `peninsula` = main zone)
> 11 août 2021 03:12
> 353MW solar production

### QA

353 MW at 03:10 🌙 look like a big value in night !

The value from ENTSOE is stable => it's the main issue: live value is frozen or not live data

### proposal
use values from REE to have 10mn live data

**Comment by gwpicard** [comment]
Hi @Manu1400 -- since the release of the new flowtracing pipeline and the changes made in https://github.com/tmrowco/electricitymap-contrib/pull/3216, we now show data in hourly buckets rather than updated in 15min intervals. We use ENTSO-E for ES data as you mentioned, but there is no urgent reason to switch to a new source that would also be averaged over the hour.

If after running some analysis you find that REE would be better for hourly, it would be great to update the parser with that data! In the meantime I will close this issue 😃
