### ISSUE TITLE
PT - Portugal Data Down 

### ISSUE THREAD

**Issue by CAVACO-PT** [tmrowco/electricitymap-contrib#3483]
Live data is temporarily unavailable for this area. Help us identify the problem by taking a look at the runtime logs, or contact our data provider.

https://storage.googleapis.com/electricitymap-parser-logs/index.html

**Comment by flixlix** [comment]
I've had the same problem since 1st of November

**Comment by cobirnm** [comment]
Same here since November 1st

**Comment by dvdme** [comment]
Same here.

Also, data seams to be available on the source: [transparency.entsoe.eu](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=16.11.2021+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=16.11.2021+00:00|CET|DAYTIMERANGE&area.values=CTY|10YPT-REN------W!BZN|10YPT-REN------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

**Comment by flixlix** [comment]
Update: Portugal's info is working again, first time since October 31st.

**Comment by CAVACO-PT** [comment]
Yes same here its working again .... thank you all for the feedback !!

**Comment by dvdme** [comment]
It is not working again. Accordingly with the history graph, it stopped working again somewhere between 1h45 and 8h00. 

![image](https://user-images.githubusercontent.com/3511881/142180518-b9b5fe86-5ce0-4832-ab5c-d465653b4e0b.png)

**Comment by flixlix** [comment]
![image](https://user-images.githubusercontent.com/61006057/142197397-40e88501-be75-4bdd-81b7-7bc18e73bdbf.png)

Weird, I have a different time, of when it became unavailable

**Comment by dvdme** [comment]
Now I also have different times:

![image](https://user-images.githubusercontent.com/3511881/142218553-5af5b43e-56f9-4fd9-bccc-6e4bf90d54d6.png)

It seams that the time flows in the X axis but the "unavailable since" gap is always the same. Maybe a UI bug?

**Comment by FelixDQ** [comment]
It is most likely because of a data delay from the provider. Portugal uses ENTSOE, so you can see the raw data on transparency.entsoe.eu:

https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=17.11.2021+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=17.11.2021+00:00|CET|DAYTIMERANGE&area.values=CTY|10YPT-REN------W!CTY|10YPT-REN------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by flixlix** [comment]
![image](https://user-images.githubusercontent.com/61006057/142390088-8d09c952-3ff6-4bca-8bc4-44bdc704ad74.png)

My CO2-Signal Home Assistant integration is sometimes available, but is very unstable
