### ISSUE TITLE
Ireland data not captured by electricity map

### ISSUE THREAD

**Issue by Wexford1** [tmrowco/electricitymap-contrib#3566]
Since several weeks Irish electricity data is missing from electricity map.  Can it be restored?

**Comment by RobinFrcd** [comment]
Because [entsoe](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=23.11.2021+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=23.11.2021+00:00|CET|DAYTIMERANGE&area.values=CTY|10YIE-1001A00010!BZN|10Y1001A1001A59C&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) is down for IE. 

See this issue: https://github.com/tmrowco/electricitymap-contrib/issues/3383
